### ISSUE TITLE
Option horizontal reading, like book

### ISSUE THREAD

**Issue by TosinRoger** [FolioReader/FolioReader-Android#10]

**Comment by Sirack** [comment]
Any progress here? Or could anyone suggest how I could go about this?

**Comment by merhawifissehaye** [comment]
+1

**Comment by TosinRoger** [comment]
I left this project, the staff that stayed did not send the modifications

**Comment by lillogoal** [comment]
How did you solve it? I'm also interested

**Comment by mahavir155** [comment]
@TosinRoger @mfissehaye @atlantis0   Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
