### ISSUE TITLE
Error: Failed to resolve: org.readium:r2-server:0.1.2

### ISSUE THREAD

**Issue by sethchhim** [FolioReader/FolioReader-Android#101]
I tried to build version `0.3.1` but it fails with this error: `Error: Failed to resolve: org.readium:r2-server:0.1.2`. Any idea how I can fix this?

**Comment by mahavir155** [comment]
@sethchhim do you have internet connection while syncing?

**Comment by sethchhim** [comment]
@mahavir155 Yes I have a solid internet connection. My other dependencies load fine but this one fails. I have also tried to create a new project with this library and the build still fails.

**Comment by sethchhim** [comment]
@mahavir155 Looked at your sample app and adding this repository lets me continue
```
repositories {
        maven { url  "http://dl.bintray.com/mobisystech/maven" }
    }
```

but I get a (unrelated from this thread) error:

```
C:\Users\Seth Chhim\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.0.0.aar\a895da8c66c146a0ca2169000c700a77\res\values\values.xml
Error:(246, 5) duplicate value for resource 'attr/font' with config ''
Error:(246, 5) resource previously defined here
```

I suspect this is because I'm using Android Studio 3 Beta 1 because I want to try out Kotlin. I will side load stable channel Android Studio 2 and let you know. Thanks for the support.

**Comment by sethchhim** [comment]
Partially Solved: It builds fine using stable Android Studio 2.3.3 with the added repository. I hope it works for Android Studio 3+ in the future but I understand that is up to Google.
