### ISSUE TITLE
[0.3.1] Not all links from the TOC goes to the right section in book.

### ISSUE THREAD

**Issue by valinaga** [FolioReader/FolioReader-Android#102]
For couple of situations, especially links with hashes they don't link to the right section in book.
https://www.dropbox.com/sh/ej5p93xof9cpxo7/AACsoLwz0RzDui8w_v8a7Wqia?dl=1
Above is a link to such a file.
The 2nd level children in TOC does not work correctly. Only the 1st level and the root work fine.
`Text/Ernesto_Sabato-Abaddon_exterminatorul-5.html#toc_marker-2-1` for instance, does not work.

**Comment by GautamChibde** [comment]
@valinaga epub book you provided at this [link](https://www.dropbox.com/sh/ej5p93xof9cpxo7/AACsoLwz0RzDui8w_v8a7Wqia?dl=1) doesn't seem to be a valid file, could u provide a valid file so that we can look into the bug.

**Comment by valinaga** [comment]
@GautamChibde here it's a new one. looks like dropbox was seeing this as a zip file.

https://drive.google.com/a/cevadesign.ro/file/d/0B6CM9Y6P_V65dGdKc1hZeU9tNzg/view?usp=sharing

**Comment by mahavir155** [comment]
@valinaga looks like we don't have access to epub file.. I have requested access, so we can test that epub..

**Comment by valinaga** [comment]
let me see how to share it better. as google drive unzip the epub.
just a sec.

**Comment by avez321** [comment]
@valinaga  the epub file is not a valid file, can i know which epub tool is been used to create this file.

**Comment by valinaga** [comment]
@avez321 Hi,

The book is ok. I just downloaded and opened in iBooks. For some reasons, dropbox add the zip extension to the epub. Just drop the zip extension after download and keep only the epub extension. Do not unzip it. Just delete the .zip from the file name. It should work with no problem.

**Comment by rajvalentino** [comment]
https://we.tl/QTHpaMrouW . check it @valinaga

**Comment by hrishikesh-kadam** [comment]
@valinaga This has been already fixed in v0.3.9
@mahavir155 We can close this issue.
