### ISSUE TITLE
Problem when importing using gradle dependency?

### ISSUE THREAD

**Issue by Maruf13** [FolioReader/FolioReader-Android#105]
how solve this problem:
My android studio version is 2.2.3
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.0-alpha1'
    compile 'com.folioreader:folioreader:0.3.1'
    testCompile 'junit:junit:4.12'
}
**problem**
Error:Failed to resolve: org.readium:r2-fetcher:0.1.2
Open File
Show in Project Structure dialog

**Comment by heinzan** [comment]
Yes.This Error happen me too.
how can solve?

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "com.heinzan.folioreader"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    testCompile 'junit:junit:4.12'

    compile 'com.folioreader:folioreader:0.3.1'
}

**Comment by GautamChibde** [comment]
@Maruf13 @heinzan add this code to your project build.gradle file
``` gradle
allprojects {
    repositories {
        jcenter()
    }
    repositories {
        maven {
            url "http://dl.bintray.com/mobisystech/maven"
        }
    }
}
```

**Comment by Maruf13** [comment]
@GautamChibde why required jar file can not execute? 
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\Maruf\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.6\2ef7b1cc34de149600f5e75bc2d5bf40de894e60\jackson-core-2.8.6.jar
	File2: C:\Users\Maruf\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.8.6\9577018f9ce3636a2e1cb0a0c7fe915e5098ded5\jackson-annotations-2.8.6.jar
	File3: C:\Users\Maruf\.gradle\caches\modules-2\files-2.1\org.jsoup\jsoup\1.10.2\33ee82e324f4b1e40167f3dc5e01234a1c5cab61\jsoup-1.10.2.jar
	File4: C:\Users\Maruf\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.8.6\c43de61f74ecc61322ef8f402837ba65b0aa2bf4\jackson-databind-2.8.6.jar

**Comment by GautamChibde** [comment]
@Maruf13 it seems the issue is a dependency conflict within the application. You can look at this post [here](https://stackoverflow.com/a/37586871/5164673).

If the issue still persists then you can provide your top level and module level build.gradle files here.

**Comment by Maruf13** [comment]
Thanks @GautamChibde  it works.

**Comment by heinzan** [comment]
Thanks @GautamChibde  it fine

**Comment by zubyf09** [comment]
@GautamChibde  when i added this 
`repositories {
        maven {
            url "http://dl.bintray.com/mobisystech/maven"
        }
    }`
getting new error 

Error:(29, 13) Failed to resolve: com.android.support:appcompat-v7:26.0.2
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Volumes/WORK/Android/WorkSpace/UbookReader/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by sdilizio** [comment]
For the duplicate file error, you can just use the following and your build.gradle app file:

android {
    packagingOptions {
        exclude 'META-INF/LICENSE'
    }
}

**Comment by angelopolotto** [comment]
I get the following problem after add Maven repository:

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\Polotto\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\1cb6f15890c9394258c40b6e23108931\res\values\values.xml
Error:(246, 5) error: duplicate value for resource 'attr/font' with config ''.
Error:(246, 5) error: resource previously defined here.
C:\Source\epubpublisher\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(491) duplicate value for resource 'attr/font' with config ''.
Error:(429) resource previously defined here.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:BUILD FAILED in 3s
Information:6 errors
Information:0 warnings
Information:See complete output in console

Anyone knows what's happening?

**Comment by Zherdmant** [comment]
I have the same problem... please we need help... anyone?

**Comment by DaskiOFF** [comment]
Anyone?

**Comment by udoy-touhid** [comment]
same here

**Comment by GautamChibde** [comment]
@udoy-touhid @DaskiOFF @Zherdmant try new version [0.3.3](https://github.com/FolioReader/FolioReader-Android/releases/tag/0.3.3)

**Comment by hemantbavle1** [comment]
It's still hapening.
Error:Failed to resolve: org.readium:r2-fetcher:0.1.2
Error:Failed to resolve: org.readium:r2-parser:0.1.2
Error:Failed to resolve: org.readium:r2-server:0.1.2
