### ISSUE TITLE
Epub file is not visible

### ISSUE THREAD

**Issue by SandeepADexoit** [FolioReader/FolioReader-Android#106]
I have specified epub file in raw folder but it doesn't get shown in FolioReader.
What should i do ?
Also can u give me a sample .epub file.

**Comment by Maruf13** [comment]
@SandeepADexoit 
Same problem

**Comment by mahavir155** [comment]
@SandeepADexoit Please paste your code.. You can find sample epub file in sample project..

**Comment by heinzan** [comment]
I think permission add in manifest.Read and Write Permission.This issue solved in my projet

**Comment by sdilizio** [comment]
Same problem. Added read and write permissions in manifest. Used the sample EPUB. FolioReader interface loads but with no EPUB.

So, I just added the following to an empty activity created by Android Studio and linked the following to a button):

    public void goRead(View view) {
        Intent intent = new Intent(NavActivity.this, FolioActivity.class);
        intent.putExtra(FolioActivity.INTENT_EPUB_SOURCE_TYPE, FolioActivity.EpubSourceType.ASSETS);
        intent.putExtra(FolioActivity.INTENT_EPUB_SOURCE_PATH, "epubs/adventures.epub");
        startActivity(intent);
    }

**Comment by mahavir155** [comment]
@sdilizio Can you check the logs for the problem and paste it here?

**Comment by heinzan** [comment]
@sdilizio.Check your epub file location and type.This solved for me.good luck

**Comment by sdilizio** [comment]
09-08 17:27:32.482 26721-26721/? E/Zygote: v2
09-08 17:27:32.482 26721-26721/? I/libpersona: KNOX_SDCARD checking this for 10035
09-08 17:27:32.482 26721-26721/? I/libpersona: KNOX_SDCARD not a persona
09-08 17:27:32.483 26721-26721/? E/Zygote: accessInfo : 0
09-08 17:27:32.483 26721-26721/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0005, [-1 -1 -4 -1 0 1]
09-08 17:27:32.484 26721-26721/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=org.bookchain.bookchain 
09-08 17:27:32.487 26721-26721/? I/art: Late-enabling -Xcheck:jni
09-08 17:27:32.501 26721-26721/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
09-08 17:27:32.504 26721-26728/? I/art: Debugger is no longer active
09-08 17:27:32.504 26721-26728/? I/art: Starting a blocking GC Instrumentation
09-08 17:27:32.525 26721-26721/? I/art: Starting a blocking GC AddRemoveAppImageSpace
09-08 17:27:32.692 26721-26721/? W/System: ClassLoader referenced unknown path: /data/app/org.bookchain.bookchain-1/lib/arm64
09-08 17:27:32.706 26721-26721/? I/InstantRun: starting instant run server: is main process
09-08 17:27:32.753 26721-26721/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-08 17:27:32.953 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: ThreadedRenderer.create() translucent=false
09-08 17:27:32.955 26721-26721/? D/InputTransport: Input channel constructed: fd=70
09-08 17:27:32.956 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: setView = DecorView@b5f90c4[NavActivity] touchMode=true
09-08 17:27:32.968 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: dispatchAttachedToWindow
09-08 17:27:32.998 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 489381282304} surfaceGenerationChanged=true
09-08 17:27:32.999 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 489381282304} hwInitialized=true
09-08 17:27:33.009 26721-26739/? D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
09-08 17:27:33.026 26721-26739/? I/OpenGLRenderer: Initialized EGL, version 1.4
09-08 17:27:33.026 26721-26739/? D/OpenGLRenderer: Swap behavior 1
09-08 17:27:33.031 26721-26739/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
09-08 17:27:33.051 26721-26721/? W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
09-08 17:27:33.057 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 489381282304} surfaceGenerationChanged=false
09-08 17:27:33.078 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
09-08 17:27:33.078 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: MSG_WINDOW_FOCUS_CHANGED 1
09-08 17:27:33.078 26721-26721/? D/ViewRootImpl@8b3afd7[NavActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 489381282304}
09-08 17:27:33.079 26721-26721/? V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@d0cb6db nm : org.bookchain.bookchain ic=null
09-08 17:27:33.079 26721-26721/? I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
09-08 17:27:33.083 26721-26734/? D/InputTransport: Input channel constructed: fd=80
09-08 17:27:33.088 26721-26721/? V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@ad5648d nm : org.bookchain.bookchain ic=null
09-08 17:27:37.207 26721-26721/org.bookchain.bookchain D/ViewRootImpl@8b3afd7[NavActivity]: ViewPostImeInputStage processPointer 0
09-08 17:27:37.207 26721-26721/org.bookchain.bookchain W/System: ClassLoader referenced unknown path: /system/framework/QPerformance.jar
09-08 17:27:37.208 26721-26721/org.bookchain.bookchain E/BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
09-08 17:27:37.208 26721-26721/org.bookchain.bookchain V/BoostFramework: BoostFramework() : mPerf = null
09-08 17:27:37.249 26721-26721/org.bookchain.bookchain D/ViewRootImpl@8b3afd7[NavActivity]: ViewPostImeInputStage processPointer 1
09-08 17:27:37.279 26721-26721/org.bookchain.bookchain D/ViewRootImpl@8b3afd7[NavActivity]: MSG_WINDOW_FOCUS_CHANGED 0
09-08 17:27:37.379 26721-26721/org.bookchain.bookchain W/Bundle: Key com.folioreader.epub_asset_path expected String but value was a java.lang.Integer.  The default value <null> was returned.
09-08 17:27:37.379 26721-26721/org.bookchain.bookchain W/Bundle: Attempt to cast generated internal exception:
                                                                 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                     at android.os.BaseBundle.getString(BaseBundle.java:995)
                                                                     at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:127)
                                                                     at android.app.Activity.performCreate(Activity.java:6942)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err: java.io.FileNotFoundException: /storage/emulated/0/folioreader/adventures/adventures.epub (Permission denied)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at java.util.zip.ZipFile.open(Native Method)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:218)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:147)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at java.util.zip.ZipFile.<init>(ZipFile.java:118)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at org.readium.r2_streamer.model.container.EpubContainer.<init>(EpubContainer.java:29)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:204)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:190)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:146)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.Activity.performCreate(Activity.java:6942)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.ActivityThread.-wrap14(ActivityThread.java)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.os.Looper.loop(Looper.java:154)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6682)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
09-08 17:27:37.402 26721-26721/org.bookchain.bookchain W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
09-08 17:27:37.414 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: ThreadedRenderer.create() translucent=false
09-08 17:27:37.416 26721-26721/org.bookchain.bookchain D/InputTransport: Input channel constructed: fd=84
09-08 17:27:37.416 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: setView = DecorView@a9d9776[FolioActivity] touchMode=true
09-08 17:27:37.418 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: dispatchAttachedToWindow
09-08 17:27:37.434 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 488854568960} surfaceGenerationChanged=true
09-08 17:27:37.434 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 488854568960} hwInitialized=true
09-08 17:27:37.435 26721-26739/org.bookchain.bookchain D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
09-08 17:27:37.472 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
09-08 17:27:37.472 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: MSG_WINDOW_FOCUS_CHANGED 1
09-08 17:27:37.473 26721-26721/org.bookchain.bookchain D/ViewRootImpl@ef3ba11[FolioActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 488854568960}
09-08 17:27:37.474 26721-26721/org.bookchain.bookchain V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@483a177 nm : org.bookchain.bookchain ic=null
09-08 17:27:37.474 26721-26721/org.bookchain.bookchain I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
09-08 17:27:37.480 26721-26721/org.bookchain.bookchain D/InputTransport: Input channel constructed: fd=89
09-08 17:27:37.480 26721-26721/org.bookchain.bookchain D/InputTransport: Input channel destroyed: fd=80
09-08 17:27:37.524 26721-26739/org.bookchain.bookchain D/OpenGLRenderer: endAllActiveAnimators on 0x71cf5cc000 (RippleDrawable) with handle 0x71cde23200
09-08 17:27:37.524 26721-26721/org.bookchain.bookchain D/ViewRootImpl@8b3afd7[NavActivity]: mHardwareRenderer.destroy()#1
09-08 17:27:37.528 26721-26721/org.bookchain.bookchain D/ViewRootImpl@8b3afd7[NavActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true

**Comment by mahavir155** [comment]
Cool, so it solved.. I will close the issue
