### ISSUE TITLE
Issue while building Gradle file

### ISSUE THREAD

**Issue by SandeepADexoit** [FolioReader/FolioReader-Android#108]
I have downloaded zip and imported it in android studio. It asked to update Gradle file and i updated it.
Now showing me this issue.
What to do ?
![image](https://user-images.githubusercontent.com/31063996/29659012-823c5acc-88da-11e7-8701-f55e9c99f399.png)

**Comment by SandeepADexoit** [comment]
Help me out. I need it quite urgently.

**Comment by mahavir155** [comment]
please use latest version 0.3.3..
