### ISSUE TITLE
Build Error com.folioreader:folioreader:0.3.1

### ISSUE THREAD

**Issue by vijildhas** [FolioReader/FolioReader-Android#111]
![untitled](https://user-images.githubusercontent.com/6582853/29739683-64b799de-8a61-11e7-900f-75c00eed4ef0.png)

**Comment by GautamChibde** [comment]
@vijildhas see issue #105

**Comment by vijildhas** [comment]
//this is my root grandle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "http://dl.bintray.com/mobisystech/maven"  //folio reader
        }
    }
}

but after sync studio will re-direct to values.xml
 <declare-styleable name="DirectionalViewpager"><attr format="string" name="direction">
this line,???????

**Comment by mahavir155** [comment]
@vijildhas please use latest version 0.3.3
