### ISSUE TITLE
Opening an epub gives me the following error

### ISSUE THREAD

**Issue by japsoftware** [FolioReader/FolioReader-Android#112]
Communication with the client broken, or an bug in the handler code
java.lang.NullPointerException: 
Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process
(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:818)

Any ideas?

**Comment by mahavir155** [comment]
Seems like some problem in parsing epub. Is it possible for you to share epub?

**Comment by japsoftware** [comment]
I have two test devices. The same ebook works on one of the devices. The device on which it fails is a Lenovo A10-30 tablet. Thanks for the help

**Comment by sdilizio** [comment]
Same error using two of the sample EPUBs included with the project. Using an emulator with API 25. 

Thought it was me until I re-cloned a fresh copy of the repository and got the same thing. 

The following error also arrives just below the one already listed above.

Few more details that weren't posted above:
com.folioreader.android.sample E/SQLiteLog: (1) no such column: rangy

and then:
 FATAL EXCEPTION: main
                                                                                Process: com.folioreader.android.sample, PID: 20452
                                                                                android.database.sqlite.SQLiteException: no such column: rangy (code 1): , while compiling: SELECT rangy FROM highlight_table WHERE pageId = 'adventures$OEBPS/Text/cover.xhtml'

**Comment by mahavir155** [comment]
You probably have previous version of FolioReader already installed. Try to uninstall previous version and then run again.

**Comment by sdilizio** [comment]
Thanks for the suggestion. I did a complete fresh clone of the repo in a separate project and still had this problem. Would it really be an older version in another project making a difference? 

As well, I'm finding that the error seems to depend on which emulator I'm running. I was running a Nexus S emulator on API 26, and everything worked fine. However, running API 25 on a Galaxy S6 emulator produced this error.

**Comment by thestr4ng3r** [comment]
It's because the WebView tries to fetch a favicon from the Readium server, which obviously fails.
