### ISSUE TITLE
Will it support swipe left-right to change page like Kindle app

### ISSUE THREAD

**Issue by dungnguyendotme** [FolioReader/FolioReader-Android#113]
As the title, will it support swipe left-right to change page like Kindle app?

**Comment by zubyf09** [comment]
@GautamChibde waiting for you answer.

**Comment by KhalidElSayed** [comment]
@mahavir155 what about this feature?

**Comment by zubyf09** [comment]
@KhalidElSayed  @dungnguyendotme they are using DirectionalViewpager in folio_activity.xml file in code change the orientation Vertical to horizontal will do left right swipe for you.

**Comment by umarF** [comment]
it changes the chapters not the page..

**Comment by mahavir155** [comment]
@zubyf09 @KhalidElSayed @dungnguyendotme @umarF   Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
