### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by blennerSilva** [FolioReader/FolioReader-Android#122]
Error:Failed to resolve: org.readium:r2-fetcher:0.1.2
<a href="openFile:/Users/blennersilva/Developer/workspaces/android/EpubReader/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

i tried compiling the mot current version and generated this error.

and compiling the 0.2.5 version the project keeps crashing
why is this happening?

**Comment by mwaqaspervez** [comment]
@blennerSilva  i am facing the same issue. how did u get to resolve this.

**Comment by berteodosio** [comment]
Please, have you solved this issue?

**Comment by blennerSilva** [comment]
maven {url "http://dl.bintray.com/mobisystech/maven"}

on your gradle

**Comment by berteodosio** [comment]
Thank you, it worked! 😄

**Comment by blennerSilva** [comment]
:)

**Comment by ikhanal** [comment]
Thank you it worked.
