### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by blennerSilva** [FolioReader/FolioReader-Android#123]
is there any way you guys can enabled horizontal scroll?

**Comment by shahabrauf18** [comment]
It may help you, https://github.com/shahabrauf18/FolioReader-Android

**Comment by blennerSilva** [comment]
i does help but its a lil outdated...is there anyway to implement it on the newest tag?

**Comment by blennerSilva** [comment]
is there anyway to adapt what you did to the latest lib?

**Comment by shahabrauf18** [comment]
Yes you can use my class HorizontalWebView instead of the ObservableWebView.

**Comment by blennerSilva** [comment]
ok i see that but how am i suppose to adapt the class that dont exist anymore such as TEXTELEMENT and somo methods of APPUTILS?

**Comment by blennerSilva** [comment]
is there anyway to implement the class without having to pretty change the whole structure of the 0.3.2 lib? i tried doing just the HorizontalwebView and HorizontalFragment....but the highlight db is completely different and other classes needed too...can you give me a guide on how to implement that on 0.3.2 i know im asking alot

**Comment by blennerSilva** [comment]
@shahabrauf18  would you interested in making a side project out off folio(paid)? if so would plz send me your email so we can talk ?

**Comment by shahabrauf18** [comment]
shahab.rauf18@gmail.com

**Comment by LeoDiasDev** [comment]
Hello guys @blennerSilva and @shahabrauf18, have you managed to adapt HorizontalWebView in the latest version of lib? I'd like to use the same functionality. Thanks

**Comment by blennerSilva** [comment]
Yes just use the class HorizontalWebView instead of the default one...or just captured the click and make it scroll vertically..it all the same.

**Comment by LeoDiasDev** [comment]
I tried to implement, but this your HorinzontalWebView class can not be used in the last version of the lib, there are methods and variables non existent in the current.

Do you have any plans to bring it to the latest version of lib?

**Comment by mahavir155** [comment]
@blennerSilva @LeoDiasDev we are working on it, but i am not sure when we'll able to complete that. But now we have initiated horizontal scroll development..

**Comment by LeoDiasDev** [comment]
@mahavir155

**Comment by RajGala** [comment]
@mahavir155  Sir is this horizontal scrolling update for both Android and Ios ??

**Comment by mahavir155** [comment]
@RajGala @LeoDiasDev We did started work on Horizontal scrolling.. Checkout feature/horizontal_scroll branch:
https://github.com/FolioReader/FolioReader-Android/tree/feature/horizontal_scroll

It still need much improvements. But you can checkout how it works and help us to contribute in horizontal scrolling :)

**Comment by LeoDiasDev** [comment]
Hello @mahavir155,

Do you can explain how to set the horizontal in this feature?

Thanks

**Comment by mahavir155** [comment]
@LeoDiasDev Horizontal feature is not released yet.. But you can test by pull the horizontal_branch.. You just need to go to settings where you can change font.. There you can see option to set scrolling mode "Horizontal or Vertical"

**Comment by RajGala** [comment]
Sir glad to have this trial version(post integration) but it has got a lot
of lagging and pagination issues... Will be happy to know when will be
realease of its right complete new version in the market!!

**Comment by RajGala** [comment]
Sir will be glad to know which files extensions are supported by folio
reader!!

**Comment by mahavir155** [comment]
@LeoDiasDev @RajGala @shahabrauf18 @blennerSilva @hebertialmeida Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration

**Comment by RTSTL** [comment]
> 

> 

> 

> 

> 

> [``](

- 

- [ ]1. url

)
