### ISSUE TITLE
Duplicate value for resource: attr/font

### ISSUE THREAD

**Issue by Semper-Viventem** [FolioReader/FolioReader-Android#127]
When working with the support library 26.1.0, there is an attribute conflict (attr/font).

` AGPBI: {"kind":"error","text":"error: duplicate value for resource \u0027attr/font\u0027 with config \u0027\u0027.","sources":[{"file":"/home/konstantin/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/92547b07694958bd73718d8755888207/res/values/values.xml","position":{"startLine":245,"startColumn":4,"startOffset":26813,"endColumn":68,"endOffset":26877}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource previously defined here.","sources":[{"file":"/home/konstantin/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/92547b07694958bd73718d8755888207/res/values/values.xml","position":{"startLine":245,"startColumn":4,"startOffset":26813,"endColumn":68,"endOffset":26877}}],"original":"","tool":"AAPT"}
/home/konstantin/WORK/source/MyApplication/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:493: error: duplicate value for resource 'attr/font' with config ''.
/home/konstantin/WORK/source/MyApplication/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:431: error: resource previously defined here.`

**Comment by thestr4ng3r** [comment]
Isn't this completely fixed by #131? If yes then the issue should be closed.

**Comment by Semper-Viventem** [comment]
@thestr4ng3r Yes, this is my pull-request. Forgot to close the branch :)
