### ISSUE TITLE
epub show image support

### ISSUE THREAD

**Issue by dtboy1995** [FolioReader/FolioReader-Android#14]
present epub file cover with image , if i want to add this feature to this project,what should the best way that  i do...please give me some suggests..

**Comment by hebertialmeida** [comment]
We already have a method to get the ePub cover image https://github.com/FolioReader/FolioReaderKit/blob/master/Example/Example/ViewController.swift#L63

Is it similar? Can you provide more details?

**Comment by nikita2423** [comment]
Working solution
[https://github.com/FolioReader/FolioReader-Android/issues/77](How to display images in Epub using Folio Reader)
