### ISSUE TITLE
I've had problem with Android Studio 3 and FolioReader

### ISSUE THREAD

**Issue by Zherdmant** [FolioReader/FolioReader-Android#145]
![image](https://user-images.githubusercontent.com/26679223/33236669-84791fea-d228-11e7-96f1-763b3e6d21f3.png)

![image](https://user-images.githubusercontent.com/26679223/33236666-6968a7ac-d228-11e7-99e9-1b3b8db7a36d.png)

![image](https://user-images.githubusercontent.com/26679223/33236632-92c6790e-d227-11e7-95a9-5d553a10173f.png)

**Comment by GautamChibde** [comment]
@Zherdmant version 0.3.2 is not stable with API level 26+ you can refer [this](https://github.com/FolioReader/FolioReader-Android/pull/131) for help.

**Comment by mahavir155** [comment]
@Zherdmant Should be fixed in latest version 0.3.3..
