### ISSUE TITLE
Text To Speech

### ISSUE THREAD

**Issue by DemonRem** [FolioReader/FolioReader-Android#147]
there is a few app that read the book this app have this ability to do that to?
I mean not part of the book

**Comment by mahavir155** [comment]
@DemonRem Sorry, not understood your question.. But yes, FR support TTS feature and if you don't need you can disable it.. For now closing the issue.. If that didn't answer your question, you can reopen it..

**Comment by abhi08singh** [comment]
Hi, 
May I know how can anyone disable the TextToSpeech Feature as it is crashing on some Android Devices.

**Comment by lampofdrog** [comment]
how can i change language of speech to french language, i mean how can change Locale support TTS?

**Comment by maheshsuthar93** [comment]
@mahavir155  Could you help me TTS is not working in your demo
