### ISSUE TITLE
Horizontal reading option not available

### ISSUE THREAD

**Issue by Mohsin92** [FolioReader/FolioReader-Android#15]
After comparing from iOS I found horizontal reading option not available.

I have found you guys are very active on iOS repo.

I request you to please give update on android too.

Thank you.

**Comment by rajvalentino** [comment]
@Mohsin92 Have you tried https://github.com/readium/SDKLauncher-Android ?

**Comment by merhawifissehaye** [comment]
@rajvalentino how do I use the repo you mentioned? What is it please?

**Comment by lillogoal** [comment]
How did you solve it? I'm also interested

**Comment by mahavir155** [comment]
@Mohsin92 @lillogoal @mfissehaye  Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
