### ISSUE TITLE
unzip folder

### ISSUE THREAD

**Issue by blennerSilva** [FolioReader/FolioReader-Android#155]
hey guys can you please help me i need to where the .epub file is unziped...im my case i need the file path of this folder so i can delete it dynamically

**Comment by blennerSilva** [comment]
i need to know the path for the OEBPS file ins this case

**Comment by mahavir155** [comment]
Epub file is not unzipped.. it is read without unzipping..On Dec 30, 2017 2:04 AM, blennerSilva <notifications@github.com> wrote:i need to know the path for the OEBPS file ins this case
