### ISSUE TITLE
Unable to find explicit activity class

### ISSUE THREAD

**Issue by GabrielLidenor** [FolioReader/FolioReader-Android#163]
> android.content.ActivityNotFoundException: Unable to find explicit activity class {com.folioreader.ui.folio.activity.FolioActivity}; have you declared this activity in your AndroidManifest.xml?

Right after trying to open an epub file with the bellow code:

>  FolioReader folioReader = new FolioReader(WebViewActivity.this);
>             folioReader.openBook(magazine.getGoogleDriveLink());

**Comment by mahavir155** [comment]
Yes, you need to declare FolioActivity in AndroidManifest.xml

**Comment by GabrielLidenor** [comment]
Thanks

**Comment by ArnoldsK** [comment]
Could you please specify details on declaring it? Defining android:name="com.folioreader.ui.folio.activity.FolioActivity" does not help.
