### ISSUE TITLE
Want to know if Horizontal scroll/flip supported??

### ISSUE THREAD

**Issue by Hardy311t3** [FolioReader/FolioReader-Android#166]
Great work guys and it will really gonna help a lot as all those old projects are ether out dated or migrated to AGPL  so it will gonna speed up the process.

Anyways,  Actually I want to know if horizontal page scrolling/flipping supported by default (setting/option by which it will be upto the end user to choose from) or through customization.

And Thank for such a great contribution to the community.

Keep up the good work guys.

**Comment by mahavir155** [comment]
@Hardy311t3 We did started work on Horizontal scrolling.. Checkout feature/horizontal_scroll branch:
https://github.com/FolioReader/FolioReader-Android/tree/feature/horizontal_scroll

It still need much improvements. But you can checkout how it works and help us to contribute in horizontal scrolling :)

**Comment by mahavir155** [comment]
@Hardy311t3  Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
