### ISSUE TITLE
Cant show images

### ISSUE THREAD

**Issue by vikasrairajput** [FolioReader/FolioReader-Android#170]
![whatsapp image 2018-02-06 at 17 56 28](https://user-images.githubusercontent.com/22234415/35859728-310776c2-0b67-11e8-901a-ccf84a77523a.jpeg)
![whatsapp image 2018-02-06 at 17 56 28 1](https://user-images.githubusercontent.com/22234415/35859740-37c2eb90-0b67-11e8-8d36-87806e6889d5.jpeg)

**Comment by LeoDiasDev** [comment]
Hello, 

Search for the method with the name **setHtml**, on the line:

`Constants.LOCALHOST + mBookTitle + "/" + path + "/" ,`

change to:

`Constants.LOCALHOST + mBookTitle + "/" + path,`

I hope that i have helped

**Comment by vikasrairajput** [comment]
Hey @LeoDiasDev  thanks for the help...image working now but book page taking extra space from left and right..how to resolve this?

**Comment by hrishikesh-kadam** [comment]
@vikasrairajput We have made the necessary changes to load images. For the extra spacing issue please report it as new issue with some description, screenshots. Also it would be helpful if you could share the EPUB file. 

@mahavir155 We can close this issue.

**Comment by nuwanchamara** [comment]
code in SetNetl() method looks like below
` private void setHtml(boolean reloaded) {
        if (spineItem != null) {
            String ref = spineItem.href;
            if (!reloaded && spineItem.properties.contains("media-overlay")) {
                mediaController.setSMILItems(SMILParser.parseSMIL(mHtmlString));
                mediaController.setUpMediaPlayer(spineItem.mediaOverlay, spineItem.mediaOverlay.getAudioPath(spineItem.href), mBookTitle);
            }
            mConfig = AppUtil.getSavedConfig(getContext());

            String path = "";
            int forwardSlashLastIndex = ref.lastIndexOf('/');
            if (forwardSlashLastIndex != -1)
                path = ref.substring(0, forwardSlashLastIndex + 1);

            String mimeType;
            if (spineItem.typeLink.equalsIgnoreCase(getString(R.string.xhtml_mime_type))) {
                mimeType = getString(R.string.xhtml_mime_type);
            } else {
                mimeType = getString(R.string.html_mime_type);
            }

            mWebview.loadDataWithBaseURL(
                    Constants.LOCALHOST + mBookTitle + "/" + path,
                    HtmlUtil.getHtmlContent(getContext(), mHtmlString, mConfig),
                    mimeType,
                    "UTF-8",
                    null);
        }
    }`


But Images re not showing
