### ISSUE TITLE
I want add mode , try this change css , js but not working

### ISSUE THREAD

**Issue by chawaphonSa** [FolioReader/FolioReader-Android#172]
help me please

**Comment by hrishikesh-kadam** [comment]
@chawaphonSa Please help us to better understand your issue.

We have added Issue Template for reporting any issues -
https://github.com/FolioReader/FolioReader-Android#reporting-issue

So please fill the template and reply back on same thread.

**Comment by mahavir155** [comment]
No reply.. Closing issue..
