### ISSUE TITLE
How to set default Horizontal scrollbar?

### ISSUE THREAD

**Issue by umakantviprak** [FolioReader/FolioReader-Android#178]
Can you guys please tell me how to set default vertical scrollbar to horizontal scrollbar?

**Comment by LeoDiasDev** [comment]
@umakantviprak Do u can explain how to set?

**Comment by LeoDiasDev** [comment]
@umakantviprak do u know how to set?

**Comment by mahavir155** [comment]
@umakantviprak Horizontal scrolling in implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
