### ISSUE TITLE
Slippage is not smooth

### ISSUE THREAD

**Issue by king3224** [FolioReader/FolioReader-Android#189]
when I slide the page , slippage is not smooth，can you some ideas for this question? thanks

**Comment by hrishikesh-kadam** [comment]
This has been fixed in v0.4.0 and was only limited to Sample app of FolioReader.
Commit - https://github.com/FolioReader/FolioReader-Android/commit/4ebc8e34e6a74a3341832fee616fbbb6057469a3

@mahavir155 we can close this issue.
