### ISSUE TITLE
image and links are not working 

### ISSUE THREAD

**Issue by kiyos1221** [FolioReader/FolioReader-Android#19]
the reader is not showing me images, audios android the links are not working what should i do

**Comment by mahavir-jain** [comment]
did you tried latest code?
Can you send epub which you tried?

**Comment by kiyos1221** [comment]
it is now working thanks buddy, on your way can you please suggest me what to do for the pagination like a book

**Comment by mahavir-jain** [comment]
Yeah, we are working on that stuff.. Soon it will be live..

**Comment by wilburt** [comment]
@kiyos1221 please how did you fix this? I am having this same problem on most epubs.

**Comment by LeoDiasDev** [comment]
Hello @mahavir155, do you already have any news about horizontal pagination?

hugs
