### ISSUE TITLE
Memory Leakage Issue

### ISSUE THREAD

**Issue by Mayank0000** [FolioReader/FolioReader-Android#196]
When I integrate it with my application. It has been giving memory leakage issue in FolioDatabaseHelper

**Comment by mahavir155** [comment]
@Mayank0000 How did you find out? using Leak Canary or any other tool?

**Comment by Mayank0000** [comment]
@mahavir155  Using LeakCanary

**Comment by hrishikesh-kadam** [comment]
@Mayank0000 Can you please tell me which FolioReader version you are using?

**Comment by Mayank0000** [comment]
@hrishikesh-kadam 0.3.2.  Actually, I had downloaded the code and then I use it.

**Comment by mahavir155** [comment]
@Mayank0000 We are releasing new version 0.3.8 which would fix the issue. Please try using latest version. Probably you can use gradle dependency..

**Comment by hrishikesh-kadam** [comment]
@Mayank0000 Please check [Clean up code](https://github.com/FolioReader/FolioReader-Android/wiki/Clean-up-code) Wiki page for more information.

**Comment by Mayank0000** [comment]
@mahavir155 Please you help me with the code.
