### ISSUE TITLE
Want to get HighlightImpl and Rengy

### ISSUE THREAD

**Issue by Divsatweapplinse** [FolioReader/FolioReader-Android#202]
Hello everyone,
I wan to get highlightImpl object and rengy object in the FolioPageFragment screen which editing the highlight for the set note.

thanks in advance.

**Comment by mahavir155** [comment]
@Divsatweapplinse you can set HighlightListener.. Check out https://github.com/FolioReader/FolioReader-Android/wiki/Highlight-Event
