### ISSUE TITLE
Same epub file appearing multiple times as adding next epub files for the same container.

### ISSUE THREAD

**Issue by techvedikasolutions** [FolioReader/FolioReader-Android#209]
Hi Mahavir,I customized the folio activity as per my requirement,but I am getting one issue,whenever I adding the epub file to the activity,its appending the same epub multiple times.First time it showing one epub and for second time add its showing 2 same epub files in same.Please suggest or guide me how can I fix this issue.

I asked this one in the same issue which i have raised previously.But I did not get any response.So I am raising this on as new one.

please guide me,its helpful for me.

Thanks in Advance.

**Comment by GautamChibde** [comment]
@techvedikasolutions please share your code and the screenshot for us to understand the issue. also if possible the epub file.

**Comment by techvedikasolutions** [comment]
Hi, I am using the same folio activity in my code,I just modified initbook method and activity xml UI according to my requirement.Below is the initbook method and attaching the screenshots.


int portNumber = getIntent().getIntExtra(Config.INTENT_PORT, com.folioreader.Constants.PORT_NUMBER);
            mEpubServer = EpubServerSingleton.getEpubServerInstance(portNumber);
            //added by sai
            **if (mEpubServer.wasStarted()) {
                mEpubServer.stop();
            }**
            mEpubServer.start();
            String path = FileUtil.saveEpubFileAndLoadLazyBook(AudioPlayer.this, mEpubSourceType, mEpubFilePath,
                    mEpubRawId, mEpubFileName);
            addEpub(path);

            String urlString = com.folioreader.Constants.LOCALHOST + bookFileName + "/manifest";
            new MainPresenter(this).parseManifest(urlString);



![screenshot_20180528-122325](https://user-images.githubusercontent.com/22232011/40601311-3d52697a-6272-11e8-8adc-3d9ba86a521a.png)
![screenshot_20180528-122236](https://user-images.githubusercontent.com/22232011/40601312-3da343cc-6272-11e8-9b63-dffa1862c460.png)


To attach epub file the issue tracker not allowed that type of file.so I am giving s3 url which i am using to load the epub. https://vidyat-qa.s3.amazonaws.com/Collections/d7b1a11bf4c92738b493bf1376e03344/e6022106e60a129650126bfe838a658f/08aa95c850f46562e8c75e7a2053d677/8bb6d3109a614671249ed8025757428a/8bb6d3109a614671249ed8025757428a.epub

**Comment by techvedikasolutions** [comment]
Hi,I fixed this issue by clearing the mSpineReferenceList on adding new epub to the container.Thank you for your support.
