### ISSUE TITLE
Crash with FolioToolbar

### ISSUE THREAD

**Issue by zhombie** [FolioReader/FolioReader-Android#211]
06-06 03:33:23.163 26855-26855/com.example.zhomart.oqyrman E/AndroidRuntime: 
FATAL EXCEPTION: 
Process: com.example.zhomart.oqyrman, PID: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.zhomart.oqyrman/com.folioreader.ui.folio.activity.FolioActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.folioreader.view.FolioToolbar

Everything was ok a month ago, but now crashes

Full information: [crash.txt](https://github.com/FolioReader/FolioReader-Android/files/2074085/crash.txt)

**Comment by hrishikesh-kadam** [comment]
Can you please tell on which Mobile / Emulator did it crashed with its Android API Level?

**Comment by zhombie** [comment]
Android Galaxy J3(2017) SM-J330F, Android OS 7.0, API level 24

**Comment by hrishikesh-kadam** [comment]
Uninstall for all the user profiles from your phone, restart and then try to install.

**Comment by hrishikesh-kadam** [comment]
This issue has been fixed in v0.4.1
Previously config themeColor was saved as res id which is not constant.
Now themeColor is saved as @ColorInt
