### ISSUE TITLE
Screen got turned off while reading 

### ISSUE THREAD

**Issue by Nikhil-z** [FolioReader/FolioReader-Android#212]
The reading activity screen of Folio reader get turned off while using more than 4 minutes . Fix i found was 
`getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);`

Unfortunalty it must be added from inside the library activity . Any possible fix ?

**Comment by mahavir155** [comment]
You can extend your activity from FolioActivity and add your flags

**Comment by Nikhil-z** [comment]
Didn't work
