### ISSUE TITLE
Config.themeColor is not applied for the Dictionary and Wikipedia model window

### ISSUE THREAD

**Issue by SonyGeorge** [FolioReader/FolioReader-Android#226]
Hi Team,
When **Config.themeColor** is applied to folio reader, color is changed every where except the 
Define window, ie when we select a word, a sub menu will appear.  _copy, highlight define and share_
and if we choose define from that menu, a popup will be displayed with heading **Dictionary and Wikipedia**.
This model window color is the default old green color, this window is not respecting the Config.themeColor value

Thanks and Regards

**Comment by hrishikesh-kadam** [comment]
Fixed in v0.4.1
