### ISSUE TITLE
TST causes a crash

### ISSUE THREAD

**Issue by Skyna** [FolioReader/FolioReader-Android#23]
When i try to use the TST the app crashes. Giving the following exception:

<img width="1100" alt="screen shot 2016-10-13 at 12 13 42" src="https://cloud.githubusercontent.com/assets/3736780/19345503/d19b954a-913e-11e6-8075-ac0655bb5e49.png">

The ePub that i use the free "The Silver Chair". I tried loading it from the assets and raw. But both is giving the same exception when i press play on TST

**Comment by mahavir-jain** [comment]
@Skyna I think, by TST, you mean to say TTS (Text-To-Speech).. TTS is not supported in 0.1 version.. It will soon be supported in 0.2 version.. Other book is audio book, so it plays audio..

But, yes, it should not crash the app on playing audio.. Infact play button should be invisible if book does not have audio :)..

**Comment by mahavir-jain** [comment]
@Skyna it will not display TTS button if book is not audio book.. Fixed in version 0.1.2
