### ISSUE TITLE
Bug when opening links.

### ISSUE THREAD

**Issue by RodPatagonia** [FolioReader/FolioReader-Android#233]
Hi,
I've found an issue when opening links in the shape of "http://127.0.0.1:8080/9789561226258/OEBPS/Text/capituloI.xhtml#toc_marker-3-3"
Those links are opened using the default browser.
Please see attached screenshot.

<img width="1151" alt="screen shot 2018-07-03 at 10 02 27 am" src="https://user-images.githubusercontent.com/40782598/42227801-4d354bd2-7eb0-11e8-8b25-f1f60d159b63.png">

**Comment by hrishikesh-kadam** [comment]
Fixed in v0.4.1
