### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by shanjiduo** [FolioReader/FolioReader-Android#234]
Why are some .epub files not open? 
![tim 20180709105708](https://user-images.githubusercontent.com/24763633/42428581-ed9aee3c-8366-11e8-93bb-8df9e624a5c5.png)

**Comment by dheerubhadoria** [comment]
Reduce the version '0.3.11' from '0.4.0' 
It will work

**Comment by shanjiduo** [comment]
@dheerubhadoria Still the same mistake!

**Comment by hrishikesh-kadam** [comment]
@shanjiduo This issue is related to EPUB Parsing. This might happen if the EPUB is invalidate or we have a bug in EPUB parsing. We are trying our best to support the invalidate EPUB file too.

Can you please share EPUB file with us so that we can investigate?

**Comment by shanjiduo** [comment]
@hrishikesh-kadam Already sent to you by email

**Comment by hrishikesh-kadam** [comment]
@shanjiduo Thanks for reporting the issue. This issue has been fixed and will get released in v0.4.1 within a week.
