### ISSUE TITLE
Font Folder is not reading in hindi epub file  while other reader opening the files correctly.

### ISSUE THREAD

**Issue by Mayank0000** [FolioReader/FolioReader-Android#238]

**Comment by hrishikesh-kadam** [comment]
@Mayank0000 Hope you have updated to v0.4.0
If in case this issue still occurs in v0.4.0 then can you please share EPUB file with us?
Also describe issue with some description and steps to reproduce it?

**Comment by Mayank0000** [comment]
Thank you so much, @hrishikesh-kadam.  Yes, the issue with the version. 

 You had saved a lot of time of mine.

**Comment by devsideal** [comment]
@hrishikesh-kadam Yes v0.4.0 well opening Hindi files but List of Hindi highlights and Hindi audio not well ?
