### ISSUE TITLE
the reader doesn't read some unicode books

### ISSUE THREAD

**Issue by kiyos12** [FolioReader/FolioReader-Android#24]
i have sample book written in Amharic, but the reader is not reading the book content

**Comment by mahavir-jain** [comment]
@kiyos12 is it possible for you to provide ebook?

**Comment by kiyos88** [comment]
change the extension to epub i change it to zip because github doesn't support epub file

**Comment by kiyos88** [comment]
github doesn't support epub file to be uploaded can i have your email please

**Comment by compass00** [comment]
https://pan.baidu.com/s/1gfnyP4f
the reader is not reading this book content .

**Comment by mahavir-jain** [comment]
@kiyos88 send it on mahavir@codetoart.com

**Comment by mahavir-jain** [comment]
@kiyos88 please send it on mahavir@codetoart.com

**Comment by compass00** [comment]
I changed "OEBPS" to "OPS" in the file :FolioPageFragment.java, AppUtil.java, it is worked now. My book's directory is different from the sample.

**Comment by mahavir-jain** [comment]
@compass00 yes, epub2 books can have such formats.. We've fixed this and will be included in 0.2 release soon..

**Comment by kiyos88** [comment]
@mahavir-jain  thank you finally i fix it by @compass00 's answer

**Comment by mahavir-jain** [comment]
fixed in 0.2.0
