### ISSUE TITLE
Do not change the font size and font for added books

### ISSUE THREAD

**Issue by AsyaLeah** [FolioReader/FolioReader-Android#243]
Hi, I'm using the version 0.4.0 

In books that are in the application font size and fint is changing
but when I add new books it doesn't work.
![screenshot_1531897833](https://user-images.githubusercontent.com/41360300/42866013-0e3ef25a-8a74-11e8-9813-c4ebe352b02b.png)
![screenshot_1531897837](https://user-images.githubusercontent.com/41360300/42866014-0e5eb5ea-8a74-11e8-8e58-698df1da94ee.png)

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah Can you please provide EPUB file for investigation?

Also now we have added Issue Template for reporting any issues -
https://github.com/FolioReader/FolioReader-Android#reporting-issue

So please fill the template and reply back on same thread.

**Comment by AsyaLeah** [comment]
is the file
[tfilat_haderech_ru_ah.zip](https://github.com/FolioReader/FolioReader-Android/files/2321412/tfilat_haderech_ru_ah.zip)

i solved it

in file Style.css

It was:

.andada {
     font-family: "andada", sans-serif;
 }
.lato {
     font-family: "lato", serif;
 }
.lora {
     font-family: "lora", serif;
 }
.raleway {
     font-family: "raleway", sans-serif;
 }

html.textSizeOne { font-size: 13px !important; }
html.textSizeTwo { font-size: 15px !important; }
html.textSizeThree { font-size: 17px !important; }
html.textSizeFour { font-size: 19px !important; }
html.textSizeFive { font-size: 21px !important; }

h1 {
    font-size: 2em;
    line-height: 1.2;
}
h2 {
    font-size: 1.5em;
    line-height: 1.2;
}
h3 {
    font-size: 1.17em;
    line-height: 1.2;
}
h4 {
    font-size: 1em;
    line-height: 1.2;
}
h5 {
    font-size: 0.83em;
    line-height: 1.2;
}
h6 {
    font-size: 0.67em;
    line-height: 1.2;
}
body {
    word-break: break-word !important;
    -webkit-hyphens: auto !important;
    hyphens: auto !important;
}
p, span, div {
    font-size: 1em;
    line-height: 1.5 !important;
}

Changed to

.andada, .andada p, .andada span, .andada div {
     font-family: "andada", sans-serif !important;
 }
.lato, .lato p, .lato span, .lato div {
     font-family: "lato", serif !important;
 }
.lora, .lora p, .lora span, .lora div {
     font-family: "lora", serif !important;
 }
.raleway, .raleway p, .raleway span, .raleway div {
     font-family: "raleway", sans-serif !important;
 }

.textSizeOne *{ font-size: 13px ; }
.textSizeOnePlus *{ font-size: 14px ; }
.textSizeTwo * { font-size: 15px ; }
.textSizeTwoPlus * { font-size: 16px ; }
.textSizeThree * { font-size: 17px ; }
.textSizeThreePlus * { font-size: 18px ; }
.textSizeFour * { font-size: 19px ; }
.textSizeFourPlus * { font-size: 20px ; }
.textSizeFive * { font-size: 21px ; }
.textSizeFivePlus * { font-size: 22px ; }

h1 {
    font-size: 2em !important;
    line-height: 1.2;
}
h2 {
    font-size: 1.5em !important;
    line-height: 1.2;
}
h3 {
    font-size: 1.17em !important;
    line-height: 1.2;
}
h4 {
    font-size: 1em !important;
    line-height: 1.2;
}
h5 {
    font-size: 0.83em !important;
    line-height: 1.2;
}
h6 {
    font-size: 0.67em !important;
    line-height: 1.2;
}
body {
    word-break: break-word !important;
    -webkit-hyphens: auto !important;
    hyphens: auto !important;
}
p, span, div {
    font-size: 1em !important;
    line-height: 1.5 !important;
}

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah You don't have to change the styling that much.
Issue has been fixed by changing font-size unit from em to rem.
This issue will get release in next release.

Thanks for submitting the issue and sharing EPUB file.

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah Issue fix released in v0.4.2

**Comment by MostafaShiri7071** [comment]
> 
> 
> is the file
> [tfilat_haderech_ru_ah.zip](https://github.com/FolioReader/FolioReader-Android/files/2321412/tfilat_haderech_ru_ah.zip)
> 
> i solved it
> 
> in file Style.css
> 
> It was:
> 
> .andada {
> font-family: "andada", sans-serif;
> }
> .lato {
> font-family: "lato", serif;
> }
> .lora {
> font-family: "lora", serif;
> }
> .raleway {
> font-family: "raleway", sans-serif;
> }
> 
> html.textSizeOne { font-size: 13px !important; }
> html.textSizeTwo { font-size: 15px !important; }
> html.textSizeThree { font-size: 17px !important; }
> html.textSizeFour { font-size: 19px !important; }
> html.textSizeFive { font-size: 21px !important; }
> 
> h1 {
> font-size: 2em;
> line-height: 1.2;
> }
> h2 {
> font-size: 1.5em;
> line-height: 1.2;
> }
> h3 {
> font-size: 1.17em;
> line-height: 1.2;
> }
> h4 {
> font-size: 1em;
> line-height: 1.2;
> }
> h5 {
> font-size: 0.83em;
> line-height: 1.2;
> }
> h6 {
> font-size: 0.67em;
> line-height: 1.2;
> }
> body {
> word-break: break-word !important;
> -webkit-hyphens: auto !important;
> hyphens: auto !important;
> }
> p, span, div {
> font-size: 1em;
> line-height: 1.5 !important;
> }
> 
> Changed to
> 
> .andada, .andada p, .andada span, .andada div {
> font-family: "andada", sans-serif !important;
> }
> .lato, .lato p, .lato span, .lato div {
> font-family: "lato", serif !important;
> }
> .lora, .lora p, .lora span, .lora div {
> font-family: "lora", serif !important;
> }
> .raleway, .raleway p, .raleway span, .raleway div {
> font-family: "raleway", sans-serif !important;
> }
> 
> .textSizeOne *{ font-size: 13px ; }
> .textSizeOnePlus *{ font-size: 14px ; }
> .textSizeTwo * { font-size: 15px ; }
> .textSizeTwoPlus * { font-size: 16px ; }
> .textSizeThree * { font-size: 17px ; }
> .textSizeThreePlus * { font-size: 18px ; }
> .textSizeFour * { font-size: 19px ; }
> .textSizeFourPlus * { font-size: 20px ; }
> .textSizeFive * { font-size: 21px ; }
> .textSizeFivePlus * { font-size: 22px ; }
> 
> h1 {
> font-size: 2em !important;
> line-height: 1.2;
> }
> h2 {
> font-size: 1.5em !important;
> line-height: 1.2;
> }
> h3 {
> font-size: 1.17em !important;
> line-height: 1.2;
> }
> h4 {
> font-size: 1em !important;
> line-height: 1.2;
> }
> h5 {
> font-size: 0.83em !important;
> line-height: 1.2;
> }
> h6 {
> font-size: 0.67em !important;
> line-height: 1.2;
> }
> body {
> word-break: break-word !important;
> -webkit-hyphens: auto !important;
> hyphens: auto !important;
> }
> p, span, div {
> font-size: 1em !important;
> line-height: 1.5 !important;
> }

In some pages the font is not applied and in some pages it was applied, which solved my problem

**Comment by MostafaShiri7071** [comment]
> 
> 
> is the file
> [tfilat_haderech_ru_ah.zip](https://github.com/FolioReader/FolioReader-Android/files/2321412/tfilat_haderech_ru_ah.zip)
> 
> i solved it
> 
> in file Style.css
> 
> It was:
> 
> .andada {
> font-family: "andada", sans-serif;
> }
> .lato {
> font-family: "lato", serif;
> }
> .lora {
> font-family: "lora", serif;
> }
> .raleway {
> font-family: "raleway", sans-serif;
> }
> 
> html.textSizeOne { font-size: 13px !important; }
> html.textSizeTwo { font-size: 15px !important; }
> html.textSizeThree { font-size: 17px !important; }
> html.textSizeFour { font-size: 19px !important; }
> html.textSizeFive { font-size: 21px !important; }
> 
> h1 {
> font-size: 2em;
> line-height: 1.2;
> }
> h2 {
> font-size: 1.5em;
> line-height: 1.2;
> }
> h3 {
> font-size: 1.17em;
> line-height: 1.2;
> }
> h4 {
> font-size: 1em;
> line-height: 1.2;
> }
> h5 {
> font-size: 0.83em;
> line-height: 1.2;
> }
> h6 {
> font-size: 0.67em;
> line-height: 1.2;
> }
> body {
> word-break: break-word !important;
> -webkit-hyphens: auto !important;
> hyphens: auto !important;
> }
> p, span, div {
> font-size: 1em;
> line-height: 1.5 !important;
> }
> 
> Changed to
> 
> .andada, .andada p, .andada span, .andada div {
> font-family: "andada", sans-serif !important;
> }
> .lato, .lato p, .lato span, .lato div {
> font-family: "lato", serif !important;
> }
> .lora, .lora p, .lora span, .lora div {
> font-family: "lora", serif !important;
> }
> .raleway, .raleway p, .raleway span, .raleway div {
> font-family: "raleway", sans-serif !important;
> }
> 
> .textSizeOne *{ font-size: 13px ; }
> .textSizeOnePlus *{ font-size: 14px ; }
> .textSizeTwo * { font-size: 15px ; }
> .textSizeTwoPlus * { font-size: 16px ; }
> .textSizeThree * { font-size: 17px ; }
> .textSizeThreePlus * { font-size: 18px ; }
> .textSizeFour * { font-size: 19px ; }
> .textSizeFourPlus * { font-size: 20px ; }
> .textSizeFive * { font-size: 21px ; }
> .textSizeFivePlus * { font-size: 22px ; }
> 
> h1 {
> font-size: 2em !important;
> line-height: 1.2;
> }
> h2 {
> font-size: 1.5em !important;
> line-height: 1.2;
> }
> h3 {
> font-size: 1.17em !important;
> line-height: 1.2;
> }
> h4 {
> font-size: 1em !important;
> line-height: 1.2;
> }
> h5 {
> font-size: 0.83em !important;
> line-height: 1.2;
> }
> h6 {
> font-size: 0.67em !important;
> line-height: 1.2;
> }
> body {
> word-break: break-word !important;
> -webkit-hyphens: auto !important;
> hyphens: auto !important;
> }
> p, span, div {
> font-size: 1em !important;
> line-height: 1.5 !important;
> }

In some pages the font is not applied and in some pages it was applied, which solved my problem
