### ISSUE TITLE
Some Links are not working

### ISSUE THREAD

**Issue by AsyaLeah** [FolioReader/FolioReader-Android#244]
Links works only inside the chapter
```
<a href='#ins31'>link1</a> -link work
<a href='section-0201.xml'>link2</a> - link doesn't work (valid link)
```

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah Can you please share EPUB file for further investigation?

Also now we have added Issue Template for reporting any issues -
https://github.com/FolioReader/FolioReader-Android#reporting-issue

So please fill the template and reply back on same thread.

**Comment by AsyaLeah** [comment]
it did not work in the version in version 0.4.0
it works in version 0.4.1
Thanks!!!

**Comment by hrishikesh-kadam** [comment]
@mahavir155 we can close this issue.
