### ISSUE TITLE
BookMark & Search Functionality

### ISSUE THREAD

**Issue by amit-maheta** [FolioReader/FolioReader-Android#247]
I want to require BookMark & Search Functionality is it possible to integrate into this library?

**Comment by mahavir155** [comment]
@amit-maheta search functionality implemented

**Comment by amit-maheta** [comment]
Thanks for your quick reply @mahavir155

**Comment by mahavir155** [comment]
No, currently it is not configurable.. But you can edit the code and simply hide that search menu item.

**Comment by amit-maheta** [comment]
@lekhrajtiwari  
Yes, hide that search menu item.

**Comment by lekhrajtiwari** [comment]
@mahavir155   @amit-maheta  thanks for the quick reply guys! as am new to coding can you please provide with some link for steps to follow?

**Comment by arthtilva** [comment]
did anyone got option for bookmark? or anyone added ?

**Comment by syedecryptr** [comment]
Bookmark feature added in the repo :

https://github.com/syedecryptr/Folioreader-Bookmark
by me.
