### ISSUE TITLE
Force going to index to select chapters

### ISSUE THREAD

**Issue by WordpressReady** [FolioReader/FolioReader-Android#248]
This is not an issue per se, but a possible feature.

I'm testing FolioReader with few epubs and the app is working very good!

However, I noticed that if I read a book, folio reader is going from page to page without need of using the index. This is made transparently which is great.

I have a particular case where I would need after the user read a entire page (which are big), go back to the index and select another one, instead allowing FolioReader enters in the next page automatically.

This is particularly for a course I'm making and my students look through one page until the end, and after they jump to another and the concept of 'infinite page' is not working very good.

What should I need to change for making FolioReader working like that?
I'm looking some way configurable , if possible. Something like 'disallow infinite scrolling'.
Is that feasible?

Thank you!

**Comment by mahavir155** [comment]
@WordpressReady You mean chapter to chapter or page to page (in case of horizontal scrolling)?
Chapter may have multiple pages (in case of horizontal scrolling).

**Comment by WordpressReady** [comment]
I mean page to page, since I have some heavy pages.
Maybe there is some event that triggers when reader goes from one page to another (?).
I'm thinking to prevent scroll in such case or warn student is going to a new page(s), or something  clever.
Thanks!

**Comment by WordpressReady** [comment]
Solved using onPageScrollStateChanged event
Thanks
