### ISSUE TITLE
how is the font changing logic works.

### ISSUE THREAD

**Issue by kiyos88** [FolioReader/FolioReader-Android#25]

**Comment by mahavir-jain** [comment]
if you look into FolioPageFragment->getHtmlContent(...); we are changing configuration such as font, fontSize and nightMode, which is in Config.java Class along with ConfigView.java

`htmlContent = htmlContent.replace("<html ", "<html class=\"" + classes + "\" ");`

and then changing the class style of html content

**Comment by mahavir-jain** [comment]
It was not an issue.. Closing..
