### ISSUE TITLE
Ability to close the reader from the outside

### ISSUE THREAD

**Issue by OlegTarashkevich** [FolioReader/FolioReader-Android#251]
Hi guys @hrishikesh-kadam @mahavir155 !
First of all thank you for the great library!

Does folio reader has ability to close itself outside of the reader.

For example I start reading the book from MainActivity, start the timer, when it finishes I call to close the reader and save read position.

If Folio Reader has no this option - what is you suggestion, how to implement it?

**Comment by OlegTarashkevich** [comment]
@mahavir155 Awesome, good to know!
When it can be implemented, I hope it's not so hard for you?

**Comment by hrishikesh-kadam** [comment]
@OlegTarashkevich Close API now live in v0.4.2

**Comment by luatnd** [comment]
Greate, but how can I listen to "book close" event? 
I posted a question here #463
I'm new to android.
