### ISSUE TITLE
saving state of reading

### ISSUE THREAD

**Issue by kiyos88** [FolioReader/FolioReader-Android#26]
how could i return to that page which i was reading after back button pressed and opening the book again in addition how to bookmark the that specific page thank you

**Comment by mahavir-jain** [comment]
@kiyos88 returning to same page after re-opening book will be fixed in upcoming releases.
@hebertialmeida have you thought of bookmarking page?

**Comment by mahavir-jain** [comment]
@kiyos88 returning to same page after re-opening the book should be fixed now.. bookmarks should be new feature.. so closing the issue..
