### ISSUE TITLE
How can I show in the highlight 50 characters before and 50 characters after?

### ISSUE THREAD

**Issue by AsyaLeah** [FolioReader/FolioReader-Android#266]
Hi team,

First of all thank you!

How can I show in the highlight 50 characters before and 50 characters after?

I want it to look like this:

----
Oct. 01, 2018 | 09:00
50_characters _before **TEXT_HIGHLIGHT** 50_characters_after
----
Thanks in advance.

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah You can modify FolioReader according to your need.
row_highlight.xml is the layout of Highlight list item.

@mahavir155 Not an issue. we can close it.
