### ISSUE TITLE
do not read books made by me, google doc, calibre, sigil and more - Android

### ISSUE THREAD

**Issue by pablo384** [FolioReader/FolioReader-Android#27]
As the title says, do not read books made by me, google doc, caliber, sigil and more

Nose not read correctly because the epub I do, even just edit text in a epub he read properly and then do not read the amendment.

Sigil use a partition with Windows 10, is configured to EPUB 3, I do not understand why not read my epub correctly.

please help!

https://youtu.be/c40JV2iBPoI

**Comment by mahavir-jain** [comment]
@pablo384 can you please send me crash report? Or if possible can you share that project on github?

**Comment by pablo384** [comment]
@mahavir-jain of course, here the link: https://github.com/pablo384/ProEduka.git

**Comment by mahavir-jain** [comment]
@pablo384 fixed in 0.2.1 version.. please check..
