### ISSUE TITLE
Epub content is shown only in one app among multiple apps (use at a time) when we use folioreader library in multiple apps(due to same port number)

### ISSUE THREAD

**Issue by techvedikasolutions** [FolioReader/FolioReader-Android#276]
I am using the folioreader sdk in multiple apps.If we use all the apps at a time epub content shows in only one app.because same port number is using in all apps to run the server(which folio reader library using to get the content from localhost server).Is there any way to solve this issue.

Issue / Feature - issue
FolioReader version -  0.39
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  in all phones
Crash / Error - 

Steps to reproduce / Describe in detail - just integrate the library in multiple apps and use the apps at a time.

**Comment by hrishikesh-kadam** [comment]
@techvedikasolutions You need to provide different port no for different apps and pass the port no by calling following method.

https://github.com/FolioReader/FolioReader-Android/blob/260865743f42575d95553cc6f468cc60b0b96e85/folioreader/src/main/java/com/folioreader/FolioReader.java#L127

**Comment by techvedikasolutions** [comment]
Presently you people statically defined the port number in the code.Even though we pass the port number from our app code.So I taken the library code to my app code and use the different port numbers to run them.But we got one doubt like if anyone(other apps) uses the same library with same port number then also we got the same issue,we maynot know whether the other apps using which port number right?.In that case do we have any alternatives for this.

**Comment by hrishikesh-kadam** [comment]
@techvedikasolutions Yes there is bug in FolioReader which has static url hitting the local server.
Currently we are busy in migrating from r2-streamer-java to r2-streamer-kotlin.
After migration to r2-streamer-kotlin we will take this bug and will come with some logic to handle your query.
