### ISSUE TITLE
Unable to display my epub file

### ISSUE THREAD

**Issue by ycsghr** [FolioReader/FolioReader-Android#284]
Issue / Feature - 
FolioReader version -  0.4.3
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error - 
![s80919-18390944](https://user-images.githubusercontent.com/34826145/45748480-75306b80-bc3b-11e8-8148-f083a789eb8d.jpg)
![s80919-18391413](https://user-images.githubusercontent.com/34826145/45748482-76fa2f00-bc3b-11e8-8bce-a2ad90c09781.jpg)
Unable to display my epub file
Steps to reproduce / Describe in detail -

**Comment by ycsghr** [comment]
help me

**Comment by ycsghr** [comment]
Come to help me personally, when my html is Chinese or the picture is Chinese, it can't be displayed.

**Comment by ycsghr** [comment]
[sikan.zip](https://github.com/FolioReader/FolioReader-Android/files/2403715/sikan.zip)
This is my epub file

**Comment by ycsghr** [comment]
Waiting online, etc.

**Comment by hrishikesh-kadam** [comment]
Hi @ycsghr!
Currently we are busy in integrating kotlin based parser.
So once that's done we will take this bug.
Many of the bugs listed by you will surely get fixed after integrating that kotlin based parser.
Probably it would take 4 weeks from now for next release.
Till then please excuse us.

**Comment by lekhrajtiwari** [comment]
@ycsghr can you help with the java code for displaying the file from the input stream

**Comment by ycsghr** [comment]
Sometimes it is not possible to accurately save the reading position

**Comment by kiranvirdiya** [comment]
Hi @hrishikesh-kadam,

Is Kotlin based parser integrated now?

**Comment by hrishikesh-kadam** [comment]
@kiranvirdiya Yes, it is live in version 0.5.1

**Comment by kiranvirdiya** [comment]
Thanks for the prompt response, @hrishikesh-kadam

**Comment by hrishikesh-kadam** [comment]
@ycsghr The book you attached in this comment https://github.com/FolioReader/FolioReader-Android/issues/284#issuecomment-423395405 is an invalid EPUB. 

content.opf file doesn't have href matching exactly to the actual files or alse they aren't URI decoded.

At the moment it would be not be possible to fetch the file from local server.
We are using nanohttpd as a local server. I have opened a issue on github repo for help - https://github.com/NanoHttpd/nanohttpd/issues/451#issuecomment-449965540

We will keep this issue open till we get some reply from nanohttpd.
