### ISSUE TITLE
appbar allignment issue

### ISSUE THREAD

**Issue by lekhrajtiwari** [FolioReader/FolioReader-Android#286]
Issue / Feature - 
FolioReader version -  
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error - 

Steps to reproduce / Describe in detail - 

![screenshot_2018-09-23-14-23-52](https://user-images.githubusercontent.com/32476181/45871112-366cf380-bdaa-11e8-8dfe-0309cad1bfce.png)
![screenshot_2018-09-23-14-49-57](https://user-images.githubusercontent.com/32476181/45872442-afba1580-bdad-11e8-846c-f2d46395485a.png)

can you please help with the alignment issue. am only able to achieve a perfect view when I add  this

<activity
            android:name="com.folioreader.ui.folio.activity.FolioActivity"
            android:configChanges="orientation|screenSize"
            android:label="@string/app_name"
            android:theme="@style/AppThem"
            tools:replace="android:theme"/>
in my manifest file!   

also am my compile SDK version 28
can you suggest support library versions

implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.android.support:design:28.0.0-rc01'
    implementation 'com.android.support:cardview-v7:28.0.0-rc01'
    implementation 'com.android.support:multidex:1.0.3'
   implementation 'com.folioreader:folioreader:0.4.3'

thank you.

**Comment by mahavir155** [comment]
@lekhrajtiwari This is still the issue with you?

**Comment by lekhrajtiwari** [comment]
@mahavir155  no I found the solution for this too! I just had to add 

<activity
            android:name="com.folioreader.ui.folio.activity.FolioActivity"
            android:configChanges="orientation|screenSize"
            android:label="@string/app_name"
            android:theme="@style/AppTheme"
            tools:replace="android:theme"/>

in my manifest file, and it just did the work!

thanks:)

**Comment by mahavir155** [comment]
Cool, thanks :). I will close this issue.
