### ISSUE TITLE
Can't open epub because icon menu missing

### ISSUE THREAD

**Issue by itsvee** [FolioReader/FolioReader-Android#294]
Issue / Feature - When `openBook` called, app crash.
FolioReader version - 0.4.4
FolioReader Stock / Modified - Stock
Android SDK - 28 
Mobile / Tablet / Emulator Info - Google Pixel 2 (mobile)
Crash / Error `'android.graphics.drawable.Drawable android.view.MenuItem.getIcon()'` 

Steps to reproduce / Describe in detail
- I setup by your step (use gradle) and run epub from R.raw. That code run in Fragment and define code in Adapter. When that Adapter run clicklistener, it had error like this 

![image](https://i.imgur.com/GlaZcMa.png)

I saw `FolioActivity.java` and check `onCreateOptionsMenu` found `R.id.itemConfig` and `R.id.itemTts` was missing. How can I fix it ? Thank you

**Comment by hrishikesh-kadam** [comment]
@itsvee I just tried integrating FolioReader in a fresh new project. Unable to reproduce this issue.

**Comment by itsvee** [comment]
@hrishikesh-kadam  Um... let me check again. thanks you

**Comment by itsvee** [comment]
Ok, I found this problem because my project had menu_main.xml in res/menu and your library had menu_main.xml too. It confuse when call menu on navigation bar. 😃

**Comment by hrishikesh-kadam** [comment]
@itsvee So what fix you did?
Renamed your menu_main.xml?
