### ISSUE TITLE
Folio Reader display too many whitespaces at bottom of page when paging in Horizontal Mode

### ISSUE THREAD

**Issue by ngokhongkn** [FolioReader/FolioReader-Android#299]
Issue / Feature - 
FolioReader version -  0.5.1
FolioReader Stock / Modified -  
Android SDK - Android Studio
Mobile / Tablet / Emulator Info -  Tablet Nexus 7 
Crash / Error - Folio Reader display too many whitespaces at bottom of page when paging in Horizontal Mode

Steps to reproduce / Describe in detail - 

Steps 1: Download Folio Reader lib, open it by Android Studio and click (OPEN EPUB ASSETS)

Steps 2: In page "The Silver Chair" I increased the font size and The bug has occurred. There is a big whitespace at the end of  every page. It seem be the ViewPager divide html document into page count.

![screenshot_1539924420](https://user-images.githubusercontent.com/28946232/47198267-76b59680-d395-11e8-944b-8c9de9ac4e68.png)
![screenshot_1539924253](https://user-images.githubusercontent.com/28946232/47198271-7b7a4a80-d395-11e8-93a5-4d4249e4b98b.png)

**Comment by ngokhongkn** [comment]
@hrishikesh-kadam 
Could you please take a look at this issue :)

**Comment by hrishikesh-kadam** [comment]
@ngokhongkn We are currently busy in integrating EPUB CFI as a locator.
It would take some time to take this issue.

**Comment by ngokhongkn** [comment]
@hrishikesh-kadam 
Thanks for your feedback. Please let me know when you finish this issue. Hope to receive your result soon.

**Comment by yhrun** [comment]
same issue
