### ISSUE TITLE
highlight redundancy in unicode books

### ISSUE THREAD

**Issue by kiyos88** [FolioReader/FolioReader-Android#30]
![screenshot_2016-10-25-15-48-00 1](https://cloud.githubusercontent.com/assets/12491404/19686627/b2b55522-9aca-11e6-978b-8c83b6ed0295.jpg)

as you can see in the picture if there are the same words in the book it highlights all if you highlight one of them

**Comment by mahavir-jain** [comment]
@kiyos88 can you check this now in 0.2.2 version?

**Comment by kiyos88** [comment]
10q its working close the issue
