### ISSUE TITLE
android.selection.js not found

### ISSUE THREAD

**Issue by yuanjunli** [FolioReader/FolioReader-Android#301]
` Unable to open asset URL: file:///android_asset/android.selection.js`

**Comment by hrishikesh-kadam** [comment]
@yuanjunli This error has been rectified in https://github.com/codetoart/FolioReader-Android/commit/08d81a0347dd86d00e5270d69e2f4f45d1540d3d and will get released in next release.

android.selection.js was a dependency in webviewMarker lib which has been removed now. I had forgoted to remove the js injection line.

This error doesn't cause any harm.

@mahavir155 We can close this issue.

**Comment by yuanjunli** [comment]
> @yuanjunli This error has been rectified in [codetoart@08d81a0](https://github.com/codetoart/FolioReader-Android/commit/08d81a0347dd86d00e5270d69e2f4f45d1540d3d) and will get released in next release.
> 
> android.selection.js was a dependency in webviewMarker lib which has been removed now. I had forgoted to remove the js injection line.
> 
> This error doesn't cause any harm.
> 
> @mahavir155 We can close this issue.

thanks for reply.
