### ISSUE TITLE
coverLink no set to publication

### ISSUE THREAD

**Issue by yuanjunli** [FolioReader/FolioReader-Android#306]
```
private fun coverLinkFromMeta(metadata: Node, publication: Publication) {
        val coverMeta = metadata.get("meta")!!.firstOrNull { it.attributes["name"] == "cover" }
        val coverId = coverMeta?.attributes?.get("content")
        val coverLink = publication.resources.firstOrNull { it.title == coverId }
        coverLink?.rel?.add("cover")
    }
```
i need the cover path to show,but the coverlink in the publication is null. i debug the code and coverLink has been found but no set for publication, if need to `publication.setCoverLink(coverLink)` after found

**Comment by hrishikesh-kadam** [comment]
@yuanjunli Yes Publication.coverLink is null, but if you call get function on it or just try to use the value then you can get coverLink. Have a look at this code - 

https://github.com/codetoart/r2-shared-kotlin/blob/22a2b93990be4d88858b1c57b4d5e5d7e515a295/r2-shared/src/main/java/org/readium/r2/shared/Publication.kt#L123-L124

**Comment by hrishikesh-kadam** [comment]
@mahavir155 We can close this bug.

@yuanjunli In case if you are still unable to get coverLink then you can reopen it.
