### ISSUE TITLE
I can not modify texts EPUB

### ISSUE THREAD

**Issue by pablo384** [FolioReader/FolioReader-Android#31]
@mahavir-jain 

as the title says, I can not change texts EPUB.
The application stops when trying to use the features of reading.

use exactly the Codico like this in the last update.

ebook here(by google doc): https://github.com/pablo384/ebook.git
video here: https://youtu.be/VY8jFxESkL4

thanks for your cooperation and work

**Comment by mahavir-jain** [comment]
@pablo384 should be fixed in 0.2.2
