### ISSUE TITLE
Failed to resolve: com.github.codetoart:r2-shared-kotlin:1.0.3-2

### ISSUE THREAD

**Issue by jayesh28589** [FolioReader/FolioReader-Android#315]
Hello,

I have added dependency link to my project and after sync it is giving me below error

`implementation "com.folioreader:folioreader:0.5.1"`

Failed to resolve: com.github.codetoart:r2-shared-kotlin:1.0.3-2

Android studio v 3.2.1
Kotlin version 1.2.51

What should be the issue ?

Thanks

**Comment by hrishikesh-kadam** [comment]
@jayesh28589 Hope you have added Jitpack repo as mentioned here - https://github.com/FolioReader/FolioReader-Android#gradle

**Comment by ducmanhss** [comment]
Hello, I got the error ERROR: Failed to resolve: com.github.codetoart: r2-shared-kotlin: 1.0.4-2
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.github.codetoart: r2-streamer-kotlin: 1.0.4-2
Show in Project Structure dialog
Affected Modules: app is in version 0.5.4 but when it comes down to 0.5.1 there is no more error, please help me
