### ISSUE TITLE
Unable to open downloaded epub file

### ISSUE THREAD

**Issue by jayesh28589** [FolioReader/FolioReader-Android#318]
Hello,

when I open my downloaded epub file.

`            var folioReader : FolioReader = FolioReader.get()
             folioReader.openBook(file.path)`

It's giving me this error.

E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/android.selection.js

Can you please help me to fix this ?

Thanks.

**Comment by hrishikesh-kadam** [comment]
Sure.
Can you please first yourself close #315 if it is resolved.

Now about this error.
Does it crashes your app?
Also read more about this in #301

**Comment by jayesh28589** [comment]
I will close #315 .

It does not crash the app, But it does not open downloaded epub file.

Thanks.

**Comment by hrishikesh-kadam** [comment]
@jayesh28589 Can you submit EPUB file for further investigation?

**Comment by jayesh28589** [comment]
@hrishikesh-kadam ,

Yes, Sure 

Below is the link for epub file.

https://drive.google.com/file/d/1xx1F3iNcumqcLH_CnAhjcy3dQrpoEpZO/view?usp=sharing

Thanks

**Comment by hrishikesh-kadam** [comment]
> It does not crash the app, But it does not open downloaded epub file and in logcat it is showing above error.

@jayesh28589 It does open the above attached EPUB with just one error of `Unable to open asset URL: file:///android_asset/android.selection.js`, which is actually just a warning than error.

**Comment by jayesh28589** [comment]
Ok, thats ok, but epub file is not opening in epub reader.

what can be issue ?

**Comment by hrishikesh-kadam** [comment]
@jayesh28589 Does it crash or you just see blank white page?

**Comment by jayesh28589** [comment]
I just see blank white page.

**Comment by hrishikesh-kadam** [comment]
Ya, so just click on the app, and the app bar will hide, and you will the content of your ebook which only has one line "Dummy PDF download".

**Comment by jayesh28589** [comment]
Ok, got it, let me check same case with other epub file also, then I will close the issue.

Thanks for your time.
