### ISSUE TITLE
library not working with minSdkVersion 19

### ISSUE THREAD

**Issue by anuragvarshney** [FolioReader/FolioReader-Android#323]
Issue / Feature - Not able to use the library if minSdkVersion is 19
FolioReader version -  0.5.1
FolioReader Stock / Modified -  Stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  Mobile
Crash / Error - * What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/0.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/1.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/2.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/3.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/4.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/5.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/6.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/7.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/8.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/9.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/10.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/11.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/12.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/13.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/14.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/15.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/16.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/17.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/18.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/19.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/20.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/22.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/23.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/24.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/25.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/26.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/27.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/28.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/29.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/30.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/31.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/32.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/33.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/34.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/35.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/36.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/37.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/38.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/39.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/40.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/41.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/42.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/43.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/44.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/45.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/46.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/47.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/48.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/55.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/56.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/57.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/58.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/59.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/60.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/61.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/62.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/63.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/64.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/65.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/66.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/67.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/68.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/69.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/70.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/71.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/72.jar, /home/anurag/AndroidStudioProjects/EpubReader/app/build/intermediates/transforms/dexBuilder/debug/73.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

Steps to reproduce / Describe in detail - 
Just keep ypur minsdkversion 19 and compile and run the project

**Comment by hrishikesh-kadam** [comment]
Not sure, we never got exceptions like these. Even we have used multidex in the sample app module.

**Comment by anuragvarshney** [comment]
so this is not the problem of multidex some of the dependencies were clashing in my project and the library so I wanted to ask that excluding those would make any difference or not?

**Comment by hrishikesh-kadam** [comment]
@anuragvarshney I did reply saying "Not sure". Because we never had any issue like that, can't comment on it.

**Comment by anuragvarshney** [comment]
@hrishikesh-kadam  thanks for your help and prompt response, closing this issue
