### ISSUE TITLE
Not working for all Epub

### ISSUE THREAD

**Issue by nikhilwork** [FolioReader/FolioReader-Android#325]
Issue / Feature - Unable to open epub that contains Toc.xhtm in OEBPS not .ncx
FolioReader version -  com.folioreader:folioreader:0.5.1
FolioReader Stock / Modified -  
Android SDK - com.folioreader:folioreader:0.5.1
Mobile / Tablet / Emulator Info -  Vivo V11, Samsung Duos
Crash / Error - Unable to load the file

Steps to reproduce / Describe in detail - 
[try1.zip](https://github.com/FolioReader/FolioReader-Android/files/2711689/try1.zip)

**Comment by goshenwells** [comment]
A few developers are keen to pay anyone willing to solve this problem
