### ISSUE TITLE
Want to Remove Copy and Share option

### ISSUE THREAD

**Issue by nikhilwork** [FolioReader/FolioReader-Android#343]
Issue / Feature - Want to remove copy and share option in Folio Reader content long press
FolioReader version -  com.folioreader:folioreader:0.5.1
FolioReader Stock / Modified -  Stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  Emulator and Mobile
Crash / Error - Want to restrict copy and share option

Steps to reproduce / Describe in detail - Long press the content and see the copy and share option.
![device-2019-01-17-152414](https://user-images.githubusercontent.com/25149156/51310636-1eae2f00-1a6d-11e9-816a-5e4eff9b6ae0.png)

**Comment by iLeafSolutionsPvtLtd** [comment]
You need to download the library. Open txt_selection.xml file and hide copy and share

**Comment by nikhilwork** [comment]
Thanks a lot. I have implemented the library and modified txt_selection.xml as per my requirement and working fine,
