### ISSUE TITLE
Storing Page number in firebase database 

### ISSUE THREAD

**Issue by ezzgamer** [FolioReader/FolioReader-Android#353]
Issue / i have been stuck at this part for so long, i need to store the page number in firebase database or sharedPreferences if possible.

PS: i'm kind of new to programming so forgive me if i make any stupid mistakes.

**Comment by NuniTelo** [comment]
Hello! I am facing the same question. Did you solve?

**Comment by ezzgamer** [comment]
i still didnt solve it :/

**Comment by NuniTelo** [comment]
Well, I found it. The library don't give you page number but it gives a indetification for a page. You can use ReadLocatorListener that they provide. Will share some code later.

**Comment by ezzgamer** [comment]
still waiting on the code :)
