### ISSUE TITLE
Menu disappearing in reading mode.  

### ISSUE THREAD

**Issue by NuniTelo** [FolioReader/FolioReader-Android#362]
Pretty much clicking everywhere shows nothing. Menu is only shown at the beginning,after that I can't open the menu, just read the book.
Is something I am missing? Doesn't seem a problem in IOS library.
Thanks.

Edit: It was a problem with my phone. Library is just fine and awesome.

**Comment by VishalNehra** [comment]
Hi, how did you fix this issue? I'm also facing the same.
