### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by shallawati** [FolioReader/FolioReader-Android#365]
Issue / Feature - Issue
FolioReader version -  0.5.4
FolioReader Stock / Modified -  Stock
Android SDK - minSdkVersion 21 targetSdkVersion 28
Mobile / Tablet / Emulator Info -  Android 9.0 Nexus 5X API 28
Crash / Error - Error

Steps to reproduce / Describe in detail - 
I have read similar issues to this issue (like #332 and #331) but neither solutions work with my project. When running the app, I get this error:
"Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-22:19 to override."

Note: My project is already migrated to AndroidX. Thanks!

**Comment by shallawati** [comment]
Issue solved

**Comment by ajays97** [comment]
Please tell me what is the solution to this?

**Comment by pravingaikwad07** [comment]
@shallawati - How to resolve it ?

**Comment by abbyl66** [comment]
How you resolve it?
