### ISSUE TITLE
Do not open the previous page after close and open same EPUB again

### ISSUE THREAD

**Issue by nuwanchamara** [FolioReader/FolioReader-Android#366]
Issue / Feature -  Open previous page 
FolioReader version -  0.5.4
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error -  Open epub from the first page. Need to open book from  previous state

Steps to reproduce / Describe in detail - 

open epub. scroll to another chapter. Close the app. reopen the book using the app.

**Comment by cezaryjurkiweicz** [comment]
Did you use ReadLocatorListener?

**Comment by mahavir155** [comment]
@nuwanchamara You using ReadLocatorListener? Please provide more information. Such statements doesn't help to debug the issue.

**Comment by nuwanchamara** [comment]
I have fixed that issue using ReadLocatorListener.

**Comment by mahavir155** [comment]
Closing this issue
