### ISSUE TITLE
Can i read the 100 lines of Sting paragraph directly without assets or raw 

### ISSUE THREAD

**Issue by imrankhanluhar** [FolioReader/FolioReader-Android#372]
Issue / Feature - 
FolioReader version -  
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error - 

Steps to reproduce / Describe in detail -

**Comment by mahavir155** [comment]
Can you please provide more details?

**Comment by mahavir155** [comment]
No reply. Closing the issue
