### ISSUE TITLE
Go to next chapter when loading and fast swipe

### ISSUE THREAD

**Issue by cezaryjurkiweicz** [FolioReader/FolioReader-Android#373]
When chapter is loading and you want to fast change page it's go to next chapter

**Comment by mahavir155** [comment]
Yeah, it will go to the next chapter if loading is not done. Not a bug

**Comment by cezaryjurkiweicz** [comment]
How can I change it? I think it's bad UX if someone want to go next page and it's open next chapter.

**Comment by SeijiFukuoka** [comment]
@cezaryjurkiweicz or @mahavir155  

Could you please, help me to change the code to avoid going to next chapter, when user scroll at right edge?

**Comment by 645h1** [comment]
@SeijiFukuoka Hi, did you solve that how to remove the scrolling chapters at right edge?

**Comment by 645h1** [comment]
Euroka :D  In case somebody need this then you have to go to the class called DirectionalViewpager then to the '@Override protected void onMeasure()' method. Next step is to find the line: "mGutterSize = Math.min(maxGutterSize, mDefaultGutterSize);" and replace with "mGutterSize = 0;".

**Comment by 645h1** [comment]
Eureka :D In case somebody need this then you have to go to the class called DirectionalViewpager then to the '@override protected void onMeasure()' method. Next step is to find the line: "mGutterSize = Math.min(maxGutterSize, mDefaultGutterSize);" and replace with "mGutterSize = 0;".
