### ISSUE TITLE
Business

### ISSUE THREAD

**Issue by JessicaAvz** [FolioReader/FolioReader-Android#39]
Hello, I would like to know if this project runs over some sort of licence or if it's open source for commercial use. It's for a little project I'm making.

**Comment by pablo384** [comment]
don't i member of this project, but i use in my personal project and is free, i think what not problem if you use this library.
the creator say me by inbox, what don't have problem.

welcome, if we more, better!

**Comment by mahavir-jain** [comment]
It is open source under BSD-3-Clause license. So you can use it with Copyright notice of FolioReader..
To know more checkout https://github.com/FolioReader/FolioReader-Android/blob/master/License.md
