### ISSUE TITLE
Are you planning to add support for pagecurl effect?

### ISSUE THREAD

**Issue by pritambarhate** [FolioReader/FolioReader-Android#43]
Hi

From the read me and from the screenshot, it seems that this library doesn't have support for page curl effect. Is there any plan to add that? 

Regards,

Pritam

**Comment by mahavir155** [comment]
Yes, horizontal scrolling of pages is planned.. But haven't thought of page curl animation.. You are welcome to contribute that if you are interested..

**Comment by eschao** [comment]
@mahavir155 I wrote a PageFlip, you can take a look my github.
but seems it is hard to be applied on your project, I just got a glimpse about your codes, looks like you use webview to render the content, I'm not very sure, but if you need any help about PageFlip lib, you can contact me, I also have some experiences about ebook reading application, hope it is useful. :)

**Comment by mahavir155** [comment]
Sure, will need to check how it can fit in WebView when we'll implement horizontal scrolling..

**Comment by icaromagalhaes** [comment]
Hello!
Any update about the horizontal scrolling?

**Comment by umarF** [comment]
any updates ?

**Comment by mahavir155** [comment]
@icaromagalhaes @umarF @pritambarhate Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
