### ISSUE TITLE
Plugin with id 'findbugs' not found using android studio 4.0

### ISSUE THREAD

**Issue by KishanViramgama** [FolioReader/FolioReader-Android#452]
Issue / Feature - Plugin with id 'findbugs' not found
FolioReader version -  Module Download 
FolioReader Stock / Modified -  
Android SDK - 29
Mobile / Tablet / Emulator Info -  
Crash / Error - Plugin with id 'findbugs' not found

Steps to reproduce / Describe in detail - 
after updating android studio 4.0 showing error FolioReader module **Plugin with id 'findbugs' not found**. but proper work android studio 3.6.2

**Comment by nuwanchamara** [comment]
findbugs plugin has [been removed ](https://docs.gradle.org/current/userguide/upgrading_version_5.html#the_findbugs_plugin_has_been_removed) in newer versions of gradle.  

in **config/quality/quality.gradle** file there is a task **find bugs** . If you remove that This might work or replace with [spot bugs](https://plugins.gradle.org/plugin/com.github.spotbugs) plugin

**Comment by KishanViramgama** [comment]
thank you for updating @manolisep
