### ISSUE TITLE
Donations to the repo and project activity

### ISSUE THREAD

**Issue by ghost** [FolioReader/FolioReader-Android#453]
Sorry to use this as an issue. But the point of discussion was about contributions to the author and the team behind the library. We see tons of developers using the open source library but we hardly see any financial contributions from the people using the library.
In order to keep the repo going, we need to work on regular financial contributions to the repo.

Open source doesn't mean free, developers are putting in their time and effort in making it happen. So it makes sense for it's users(us) to make financial contributions if not code, so that the project can sustain. Folioreader is a nice library, let's support the repo !

We at mooka-ventures have started with small recurring monthly contributions and also one time contributions to the repo recently.
Comment on this issue if you are doing an active financial contributions or if you plan to do so. If the donations start, then we can request the author to look into the issues and the bugs/features for the library.

Donations link: https://github.com/FolioReader/FolioReader-Android/blob/master/README.md#donations

**Comment by PatrickPrakash** [comment]
Okay we will contribute, but can you guys fix the pending issues

**Comment by PatrickPrakash** [comment]
The build is failing
