### ISSUE TITLE
Vulnerable JavaScript libraries:  Name	Version 	Known issues	Identified files jquery	3.1.1	SNYK-JS-JQUERY-174006	assets/js/jquery-3.1.1.min.js

### ISSUE THREAD

**Issue by iamjpsharma** [FolioReader/FolioReader-Android#471]
Steps to reproduce / Describe in detail - 

used latest dependency and play-store show following warning

Vulnerable JavaScript libraries:
Name	Version 	Known issues	Identified files
jquery	3.1.1	SNYK-JS-JQUERY-174006	assets/js/jquery-3.1.1.min.js

![image](https://user-images.githubusercontent.com/16868804/90221034-03f99300-de27-11ea-9fe6-c4fcced12563.png)

**Comment by KishanViramgama** [comment]
@iamjpsharma https://github.com/FolioReader/FolioReader-Android/pull/417 check this updated jQuery
