### ISSUE TITLE
Error at open project or add dependency

### ISSUE THREAD

**Issue by djinnjuank** [FolioReader/FolioReader-Android#49]
Hi 
When i try to open the Folio Reader project, i get the following error message
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0

When i try to add the dependency  compile 'com.folioreader:folioreader:0.2.3' to a sample project i get the following message
Error:(7, 13) Failed to resolve: com.folioreader:folioreader:0.2.3

What could be the problem?

Regards

**Comment by mahavir155** [comment]
Were you connected to internet when you sync gradle after adding FolioReader dependency?
also use latest FolioReader version 0.2.4?

**Comment by djinnjuank** [comment]
Hi, yes i have internet connection.
I try with the following version: com.folioreader:folioreader:0.2.4 , com.folioreader:folioreader:0.2.5 and get the same error.
Then i try:   compile 'com.folioreader:folioreader:+',  This way I could use your library and it is functional.

Regards.

**Comment by mahavir155** [comment]
@djinnjuank there seems to be some problem with jcenter.. Library has stopped syncing with jcenter for some reason.. Have contacted jcenter support.

**Comment by mahavir155** [comment]
fixed
