### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by akbarasif43** [FolioReader/FolioReader-Android#50]
I am using this library to show a epub from asset folder. So I wrote below code according to documentation which is available at Github page. 

`private void openEpub(FolioActivity.EpubSourceType sourceType,String path,int rawID) {
        Intent intent = new Intent(this, FolioActivity.class);
        if(rawID!=0) {
            intent.putExtra(FolioActivity.INTENT_EPUB_SOURCE_PATH, rawID);
        } else {
            intent.putExtra(FolioActivity.INTENT_EPUB_SOURCE_PATH, path);
        }
        intent.putExtra(FolioActivity.INTENT_EPUB_SOURCE_TYPE, sourceType);
        startActivity(intent);
    }`

But when I run my application It is showing ActivityNotFoundException - Unable to find explicit activity class {com.****.****/com.folioreader.activity.FolioActivity}; have you declared this activity in your AndroidManifest.xml?.
How can I fix this problem?

**Comment by umair151** [comment]
Can you please post the solution here?

**Comment by rajvalentino** [comment]
declare your activity name in your AndroidManifest.xml
<application
....
....
<activity android:name=".youractivityname" />
....
</application>

**Comment by rajvalentino** [comment]
Declare your activity name in `AndroidManifest.xml`
 `<application`
....
 `<activity android:name=".youracitivityname" />`
....
`</application>`

**Comment by umair151** [comment]
It was not showing in intellisense, here is the solution: 

```
<activity
            android:name="com.folioreader.activity.FolioActivity"
            android:label="@string/app_name"
            android:configChanges="orientation|screenSize">
</activity>
```
