### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by riseLishan** [FolioReader/FolioReader-Android#55]
Error:A problem occurred configuring project ':readbook'.
> Could not resolve all dependencies for configuration ':readbook:_debugCompile'.
   > Could not find com.folioreader:folioreader:0.2.5.
     Searched in the following locations:
         file:/D:/as/gradle/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.pom
         file:/D:/as/gradle/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.jar
         https://jcenter.bintray.com/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.pom
         https://jcenter.bintray.com/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.jar
         file:/E:/android-sdk-windows/android-sdk-windows/extras/android/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.pom
         file:/E:/android-sdk-windows/android-sdk-windows/extras/android/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.jar
         file:/E:/android-sdk-windows/android-sdk-windows/extras/google/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.pom
         file:/E:/android-sdk-windows/android-sdk-windows/extras/google/m2repository/com/folioreader/folioreader/0.2.5/folioreader-0.2.5.jar
     Required by:
         Reader:readbook:unspecified

**Comment by mahavir155** [comment]
@riseLishan  there seems to be some problem with jcenter.. Library has stopped syncing with jcenter for some reason.. Have contacted jcenter support.

**Comment by mahavir155** [comment]
fixed..
