### ISSUE TITLE
Font size is not changing and application is crashing when changing font size.

### ISSUE THREAD

**Issue by akbarasif43** [FolioReader/FolioReader-Android#57]
When user changed seekbar the library is calling onConfigChange method
` @Override
    public void onConfigChange() {

        int position = mFolioPageViewPager.getCurrentItem();
        //reload previous, current and next fragment
        Fragment page;
        if (position != 0) {
            page = getFragment(position - 1);
            ((FolioPageFragment) page).reload();
        }
        page = getFragment(position);
        ((FolioPageFragment) page).reload();
        if (position < mSpineReferences.size()) {
            page = getFragment(position + 1);
            if(page!=null) {
                ((FolioPageFragment) page).reload();
            }

        }
    }`

But the problem is for this statement "((FolioPageFragment) page).reload(); " because it is returning null fragment. How to fix this problem?

**Comment by mahavir155** [comment]
we can't able to reproduce this.. which version you are working on?

**Comment by akbarasif43** [comment]
I downloaded the library from github and tried to integrate that. So it is showing same error in all devices. Event I have tested the sample project. It is also crashing when I am trying to change the font. May be I am missing something. If you do not face this kind of situation could you please send me a demo apk file to test in my device?

**Comment by mahavir155** [comment]
Are you using latest source from master branch?

**Comment by akbarasif43** [comment]
As I have downloaded the source from Github, so I am assuming it was downloaded from master branch because Github shows master branch by default.

**Comment by mahavir155** [comment]
well, we have removed the code which you are pointing to.. So, i doubt if you using latest code from master branch..
