### ISSUE TITLE
Search keyword inside the book

### ISSUE THREAD

**Issue by daniyarmukhanov** [FolioReader/FolioReader-Android#61]
Anybody tried to implement search feature? Where to start if I want to implement myself?

**Comment by mahavir155** [comment]
@daniyarmukhanov checkout https://github.com/taku33/FolioReaderPlus.. This guy has implemented search in iOS..
I think you can start by looking at his code and see how it works.. And probably try to replicate same here for android..

**Comment by hrishikesh-kadam** [comment]
@daniyarmukhanov Search feature is live in v0.4.1
@mahavir155 we can close this issue.
