### ISSUE TITLE
It seems it doesn't support Img tag now?

### ISSUE THREAD

**Issue by caprice** [FolioReader/FolioReader-Android#74]
As title mentions, I have some image icon need to be shown in epub. It displays correctly in iBooks, but not when using this library.

**Comment by nikita2423** [comment]
Working solution
[How to display image in Folio Reader using Epub](https://github.com/FolioReader/FolioReader-Android/issues/77)

**Comment by mahavir155** [comment]
should be fixed now with v0.3.1
