### ISSUE TITLE
Enable Horizontal Scroll Only for Book Reading

### ISSUE THREAD

**Issue by dawoodmughal7** [FolioReader/FolioReader-Android#81]
I'm trying to **disable Vertical Scroll** and only **enable Horizontal Scroll**. This is _possible on iOS_ but not in Android. How I'll be able to enable **Horizontal Scroll**?

P.S: I've tried using HorizontalViewPager class and minor changes to ObservableWebView but nothing is working. Please do provide your support.

**Comment by lillogoal** [comment]
How did you solve it? I'm also interested

**Comment by dawoodmughal7** [comment]
I'm unable to solve it currently. Looking forward for this lib Author to provide any details if we can enable Horizontal Scroll in Folio Reader. The problem is, a single chapter can scroll vertically, but all chapters scroll horizontally (due to a ViewPager hierarchy used for managing such purpose). But in iOS, the book is converted all into Horizontal Scroll, which I'm unable to obtain in Android.

Looking forward for any sort of help in this regards!

**Comment by lillogoal** [comment]
Ok ty.
If you solve it please tell me

**Comment by blennerSilva** [comment]
is there any update about this issue? i really need this to be horizontaly

**Comment by lillogoal** [comment]
i don't know sorry!!

**Comment by mahavir155** [comment]
@lillogoal @blennerSilva @dawoodmughal7   Horizontal scrolling is implemented in v0.4.0. Please change it to version 0.4.0 to start using horizontal scrolling.. Checkout documentation https://github.com/FolioReader/FolioReader-Android/wiki/Custom-Configuration
