### ISSUE TITLE
If table of content has more than one child, it's doesn't show them 

### ISSUE THREAD

**Issue by umerk44** [FolioReader/FolioReader-Android#85]
I've notice in the scenario where we have more than one child in table of content it's doesn't show the child component, it only shows parent component.

**Comment by valinaga** [comment]
Yes, that's pretty bad. However, when the book is loaded, the lib is building the TOC as html file recursively, and save it locally in the book folder. However, in the content highlight activity it passes the original toc to the list. If there are children, none will be shown. Pretty bad. :(

**Comment by mahavir155** [comment]
I think it should be fixed now.. @umerk44 @valinaga can you please confirm?

**Comment by valinaga** [comment]
@mahavir155 
Yes, that's fixed now. However it will be benefic if the TOC will be expanded when in Contents.
I have books with only one element at the root and it looks pretty bad.

**Comment by mahavir155** [comment]
@valinaga thanks for feedback.. can you create separate ticket for same? ticket with screenshot will help..
for now i am closing this ticket

**Comment by AdarshYadav** [comment]
Can anyone the version in which we fixed this issue ?
