### ISSUE TITLE
Font size doesn't change for whole book

### ISSUE THREAD

**Issue by tungdx** [FolioReader/FolioReader-Android#87]
Only current chapter or next chapter is effected by changing the font size. The before the current chapter isn't. Hope to get a solution

**Comment by admin-vividlipi** [comment]
Dear Team, We are looking for support to get font or day/night changes applied to all chapters and pages. This is not working in our implementation. can someone support in this regards

Regards
Pramod

**Comment by valinaga** [comment]
@tungdx @admin-vividlipi the day/night issue is still there. I change the visibility of the layout in view_confi.xml to gone at least to not show the users the option. Better no option than a broke one. 
With the font size, it's pretty bad. I don't want to remove this option. Will still try to look into it. If I find a solution will let you know.

**Comment by mahavir155** [comment]
@tungdx @admin-vividlipi @valinaga 
can you please check if new version 0.3.1 have this issue?

**Comment by valinaga** [comment]
@mahavir155 
It looks like the night mode is preserved across chapter as well as font size and font family.
This issue can be closed now.
Thanks
