### ISSUE TITLE
How to change default Green color in Folio UI

### ISSUE THREAD

**Issue by harishsave** [FolioReader/FolioReader-Android#93]
I want to change the default Green color in Folio viewer UI. How to do that?

**Comment by valinaga** [comment]
@harishsave it was indeed challenging! :)
First I modified all the icons in the resources, those in green. Pay attention that icon_font has different resolutions. you need to modify them all.
Then I changed the app color. Best is to search for green in the whole project and try to replace each appearance and see what's happening.
Good luck.

**Comment by arthurlataks** [comment]
```
Config config = new Config.ConfigBuilder()
    .themeColor(0x7f0d000d)
    .build();
    
this.folioReader.openBook(filePath, config);
```

**Comment by mahavir155** [comment]
Yes, this way you can change default color..

**Comment by arthurlataks** [comment]
As I later found out (sorry, not an android dev here) this is a bad way of doing this. Currently working with React Native project, so I created a colors.xml file under res/values, then added there definition of a color I want to use like this: 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="folioReaderTheme">#6b6b6b</color>
</resources>
```

and then used the color as follows:

```
import mypackagename.R;

...

.themeColor(R.color.folioReaderTheme)

...

```

**Comment by dev-pradeep** [comment]
now its changed to  .setThemeColorInt() /  .setThemeColorRes()
