### ISSUE TITLE
[TOC issue] no link between TOCReference and SpineReferene

### ISSUE THREAD

**Issue by valinaga** [FolioReader/FolioReader-Android#98]
Hi,

I have a problem with the TOC.
The href in TOC looks like this:
`Text/Ernesto_Sabato-Abaddon_exterminatorul-5.html#toc_marker-2-1` (note the# and marker)  
but the spines hrefs are like this:
`Text/Ernesto_Sabato-Abaddon_exterminatorul-5.html`
The code for the TOC will jump to the nearest spine based on same reference title, and not on the actual TOC.
Any suggestion how to fix this issue?
Thanks.

**Comment by mahavir155** [comment]
@valinaga can you please check above bug with version 0.3.1?

**Comment by valinaga** [comment]
@mahavir155 thank!
Now it's ok. Even the TOC is now full. I used to add it as a list recursively. 
Need to look into it to make the TOC tree expanded. It looks better that way.
But this issue can be closer.
Thanks again.
